import { Button, Drawer, Select, Tag } from "../../ui";
import type { ItemAction, ItemResult, RunAccepted, RunItem, RunStatus, RunTrigger, SourceRecord, SourceRun } from "../model/sourceModels";
import { acceptedRequestSummary, safeSourceUri } from "../model/sourceProjection";
import ReferenceText from "./ReferenceText";

type ErrorView = import("../model/sourceProjection").SourceErrorView;
interface Props { source: SourceRecord; runs: SourceRun[]; status: string; error: ErrorView | null; runStatus?: RunStatus; trigger?: RunTrigger; nextCursor: string | null; hasPrevious: boolean; paging: boolean; selectedRun: SourceRun | null; items: RunItem[]; itemsNextCursor: string | null; hasPreviousItems: boolean; itemsPaging: boolean; detailLoading: boolean; itemResult?: ItemResult; itemAction?: ItemAction; retrying: boolean; lastAccepted: RunAccepted | null; onRefresh: () => void; onNext: () => void; onPrevious: () => void; onFilters: (filters: { status?: RunStatus; trigger?: RunTrigger }) => void; onSelect: (run: SourceRun) => void; onClose: () => void; onNextItems: () => void; onPreviousItems: () => void; onItemFilters: (filters: { result?: ItemResult; action?: ItemAction }) => void; onRetry: (run: SourceRun) => void; }
const runLabels: Record<RunStatus, string> = { running: "运行中", completed: "运行完成", failed: "运行失败", incomplete: "不完整", dry_run: "演练完成", superseded: "已被代次取代" };
const executionLabels = { pending: "等待执行", executing: "正在执行", failed: "执行尝试失败", completed: "执行已结束" } as const;
const triggerLabels = { manual: "手动", scheduled: "计划触发", retry: "重试" } as const;
const resultLabels: Record<ItemResult, string> = { completed: "完成", failed: "失败", skipped: "跳过", suppressed: "抑制", dry_run: "演练", queued: "已排队" };
function when(value: string | null): string { return value ? new Date(value).toLocaleString("zh-CN") : "—"; }

export default function RunHistoryPanel(props: Props) {
  const { source, runs, selectedRun } = props; const accepted = props.lastAccepted ? acceptedRequestSummary(props.lastAccepted) : null;
  const canRetry = Boolean(selectedRun && source.status === "active" && selectedRun.status === "failed" && selectedRun.source_generation === source.generation);
  return <section className="source-runs" aria-labelledby="source-runs-title">
    <div className="source-section-heading"><div><span className="source-eyebrow">EXECUTION LEDGER / G{source.generation}</span><h2 id="source-runs-title">{source.name} 的运行历史</h2></div><Button size="small" disabled={props.paging} onClick={props.onRefresh}>刷新</Button></div>
    <p className="source-safe-note">操作权限由 Source API 按当前操作者角色判定；前端不推测管理权限。</p>
    {props.error ? <div role="alert" className="source-inline-warning"><strong>{props.error.title}</strong><span>{props.error.description}</span></div> : null}
    {accepted && props.lastAccepted ? <div role="status" className="source-accepted"><strong>{accepted.action}</strong><span>{accepted.current}</span><ReferenceText value={props.lastAccepted.run_id} label="运行引用"/></div> : null}
    <div className="source-run-filters"><label>运行状态<Select aria-label="运行状态" value={props.runStatus ?? ""} options={[{ label: "全部状态", value: "" }, ...Object.entries(runLabels).map(([value, label]) => ({ value, label }))]} onChange={(value: string) => props.onFilters({ status: value ? value as RunStatus : undefined, trigger: props.trigger })}/></label><label>触发方式<Select aria-label="触发方式" value={props.trigger ?? ""} options={[{ label: "全部触发", value: "" }, ...Object.entries(triggerLabels).map(([value, label]) => ({ value, label }))]} onChange={(value: string) => props.onFilters({ status: props.runStatus, trigger: value ? value as RunTrigger : undefined })}/></label></div>
    <div className="source-table-owner" tabIndex={0} role="region" aria-label="来源运行历史表格，可横向滚动"><table className="source-data-table"><caption>来源运行历史，每页十条</caption><thead><tr><th>运行</th><th>状态</th><th>执行</th><th>尝试</th><th>代次围栏</th><th>计数</th><th>开始</th><th>操作</th></tr></thead><tbody>{props.status === "loading" ? <tr><td colSpan={8}>正在加载运行记录…</td></tr> : runs.length ? runs.map((run) => <tr key={run.id}><td><ReferenceText value={run.id} label="运行引用"/></td><td><Tag color={run.status === "failed" ? "error" : run.status === "completed" ? "success" : "warning"}>{runLabels[run.status]}</Tag><small>{triggerLabels[run.trigger]}{run.dry_run ? " · 演练" : ""}{run.force_full ? " · 全量" : ""}</small></td><td><Tag>{executionLabels[run.execution_state]}</Tag></td><td>{run.execution_attempts}</td><td><span className={run.source_generation === source.generation ? "source-fence is-current" : "source-fence is-stale"}>来源 G{run.source_generation} / 数据集 G{run.dataset_generation}</span></td><td>{run.counts.ingested} 入库 / {run.counts.failed} 失败</td><td>{when(run.started_at)}</td><td><Button size="small" onClick={() => props.onSelect(run)}>详情</Button></td></tr>) : <tr><td colSpan={8}>当前筛选条件下没有运行记录</td></tr>}</tbody></table></div>
    <div className="source-cursor-nav"><Button size="small" disabled={props.paging || !props.hasPrevious} onClick={props.onPrevious}>上一页</Button><span>每页 10 条 · Keyset cursor</span><Button size="small" disabled={props.paging || !props.nextCursor} onClick={props.onNext}>下一页</Button></div>
    <Drawer open={Boolean(selectedRun)} title="运行详情" onClose={props.onClose} width="min(760px, 96vw)" className="source-run-drawer"><>{selectedRun ? <div className="source-run-detail">
      <div className="source-run-detail-grid"><div><span>运行状态</span><b>{runLabels[selectedRun.status]}</b></div><div><span>执行状态</span><b>{executionLabels[selectedRun.execution_state]}</b></div><div><span>执行尝试</span><b>{selectedRun.execution_attempts}</b></div><div><span>代次围栏</span><b>来源 G{selectedRun.source_generation} / 数据集 G{selectedRun.dataset_generation}</b></div><div><span>持续时间</span><b>{selectedRun.duration_ms} ms</b></div><div><span>结束时间</span><b>{when(selectedRun.finished_at)}</b></div></div>
      <p className="source-capability-gap">API 未提供下次尝试时间或退避时长</p>{selectedRun.fetch_error || selectedRun.execution_last_error ? <div role="alert" className="source-run-error">{selectedRun.fetch_error || selectedRun.execution_last_error}</div> : null}
      {canRetry ? <Button type="primary" loading={props.retrying} onClick={() => props.onRetry(selectedRun)}>重试失败运行</Button> : null}
      <div className="source-run-filters"><label>项目结果<Select aria-label="项目结果" value={props.itemResult ?? ""} options={[{ label: "全部结果", value: "" }, ...Object.entries(resultLabels).map(([value, label]) => ({ value, label }))]} onChange={(value: string) => props.onItemFilters({ result: value ? value as ItemResult : undefined, action: props.itemAction })}/></label><label>项目动作<Select aria-label="项目动作" value={props.itemAction ?? ""} options={[{ label: "全部动作", value: "" }, { label: "写入", value: "upsert" }, { label: "跳过", value: "skip" }, { label: "删除", value: "delete" }]} onChange={(value: string) => props.onItemFilters({ result: props.itemResult, action: value ? value as ItemAction : undefined })}/></label></div>
      <div className="source-table-owner" tabIndex={0} role="region" aria-label="运行项目表格，可横向滚动"><table className="source-data-table"><caption>运行项目，每页十条</caption><thead><tr><th>文档引用</th><th>外部引用</th><th>来源</th><th>动作</th><th>结果</th><th>片段</th><th>错误</th></tr></thead><tbody>{props.detailLoading ? <tr><td colSpan={7}>正在加载运行项目…</td></tr> : props.items.length ? props.items.map((item) => <tr key={`${item.doc_id}:${item.external_id}:${item.created_at}`}><td><ReferenceText value={item.doc_id} label="文档引用"/></td><td>{item.external_id}</td><td>{safeSourceUri(item.source_uri)}</td><td>{item.action}</td><td>{resultLabels[item.result]}</td><td>{item.chunk_count}</td><td>{item.error_message || item.error_code || "—"}</td></tr>) : <tr><td colSpan={7}>该页没有运行项目</td></tr>}</tbody></table></div>
      <div className="source-cursor-nav"><Button size="small" disabled={props.itemsPaging || !props.hasPreviousItems} onClick={props.onPreviousItems}>上一页项目</Button><span>每页 10 条</span><Button size="small" disabled={props.itemsPaging || !props.itemsNextCursor} onClick={props.onNextItems}>下一页项目</Button></div>
    </div> : null}</></Drawer>
  </section>;
}
