import { useEffect, useRef, useState } from "react";
import { Input, Modal, Select, Switch } from "../../ui";
import type { GitHubRepoConfig, LocalDirConfig, SourceCreate, SourceKind, SourcePatch, SourceRecord } from "../model/sourceModels";
import type { SourceErrorView } from "../model/sourceProjection";

interface Props { open: boolean; source: SourceRecord | null; saving: boolean; error: SourceErrorView | null; onClose: () => void; onSave: (payload: SourceCreate | Omit<SourcePatch, "expected_generation">) => Promise<boolean>; }
type Errors = Record<string, string>;
const repoPattern = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/;
const hasNul = (value: string) => value.includes("\0");
const splitLines = (value: string) => value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean);
function parseExtensions(value: string): string[] | null { const values = value.split(/[\s,]+/).map((item) => item.trim().toLowerCase()).filter(Boolean).map((item) => item.startsWith(".") ? item : `.${item}`); return values.length ? Array.from(new Set(values)) : null; }
function safeCredential(value: string): boolean { if (value.length < 10 || value.length > 2048 || hasNul(value)) return false; try { const parsed = new URL(value); return ["secret:", "vault:"].includes(parsed.protocol) && Boolean(parsed.hostname) && Boolean(parsed.pathname.replace(/\//g, "")) && !parsed.username && !parsed.password && !parsed.search && !parsed.hash; } catch { return false; } }
function text(config: Record<string, unknown>, key: string, fallback = ""): string { return typeof config[key] === "string" ? String(config[key]) : fallback; }
function number(config: Record<string, unknown>, key: string, fallback: number): number { return typeof config[key] === "number" ? Number(config[key]) : fallback; }
const focusLabels: Record<string, string> = { name: "来源名称", path: "本地目录", repo: "GitHub 仓库", ref: "Git 引用", include: "包含规则", exclude: "排除规则", extensions: "扩展名", maxFiles: "最大文件数", stripPrefix: "Strip prefix", timeout: "超时（秒）", credential: "凭据引用" };

export default function SourceEditorDrawer({ open, source, saving, error, onClose, onSave }: Props) {
  const [name, setName] = useState(""); const [kind, setKind] = useState<SourceKind>("local_dir"); const [enabled, setEnabled] = useState(true);
  const [path, setPath] = useState(""); const [repo, setRepo] = useState(""); const [ref, setRef] = useState("main"); const [include, setInclude] = useState(""); const [exclude, setExclude] = useState(""); const [extensionText, setExtensionText] = useState(""); const [maxFiles, setMaxFiles] = useState("0"); const [stripPrefix, setStripPrefix] = useState(""); const [timeout, setTimeoutValue] = useState("300"); const [mode, setMode] = useState<"auto" | "tarball" | "api">("auto"); const [credentialRef, setCredentialRef] = useState(""); const [errors, setErrors] = useState<Errors>({}); const opener = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!open) return; opener.current = document.activeElement as HTMLElement | null; const config = source?.config ?? {}; setName(source?.name ?? ""); setKind(source?.kind ?? "local_dir"); setEnabled(source?.status !== "disabled"); setPath(text(config, "path")); setRepo(text(config, "repo")); setRef(text(config, "ref", "main")); setInclude(Array.isArray(config.include) ? config.include.join("\n") : ""); setExclude(Array.isArray(config.exclude) ? config.exclude.join("\n") : ""); setExtensionText(Array.isArray(config.extensions) ? config.extensions.join(", ") : ""); setMaxFiles(String(number(config, "max_files", 0))); setStripPrefix(text(config, "strip_prefix")); setTimeoutValue(String(number(config, "timeout", 300))); setMode(text(config, "mode", "auto") as "auto" | "tarball" | "api"); setCredentialRef(text(config, "credential_ref")); setErrors({}); }, [open, source]);
  const close = () => { if (saving) return; onClose(); queueMicrotask(() => opener.current?.focus()); };
  const save = async () => {
    const next: Errors = {}; const includeValues = splitLines(include); const excludeValues = splitLines(exclude); const ext = parseExtensions(extensionText);
    if (!name.trim()) next.name = "来源名称不能为空。"; else if (name.length > 128 || hasNul(name)) next.name = "来源名称最多 128 字符且不能包含 NUL。";
    if (kind === "local_dir") { if (!path.trim()) next.path = "本地目录不能为空。"; else if (hasNul(path)) next.path = "本地目录不能包含 NUL 字符。"; else if (path.length > 2048) next.path = "本地目录最多 2048 字符。"; }
    if (kind === "github_repo") { if (!repoPattern.test(repo.trim()) || repo.length > 256 || hasNul(repo)) next.repo = "仓库必须使用 owner/repository 格式。"; if (!ref.trim() || ref.length > 256 || hasNul(ref)) next.ref = "Git 引用必须为 1 到 256 个无 NUL 字符。"; if (stripPrefix.length > 1024 || hasNul(stripPrefix)) next.stripPrefix = "Strip prefix 最多 1024 字符且不能包含 NUL。"; }
    if (includeValues.length > 256) next.include = "包含规则最多 256 条。"; else if (hasNul(include)) next.include = "包含规则不能包含 NUL 字符。";
    if (excludeValues.length > 256) next.exclude = "排除规则最多 256 条。"; else if (hasNul(exclude)) next.exclude = "排除规则不能包含 NUL 字符。";
    if ((ext?.length ?? 0) > 64) next.extensions = "扩展名最多 64 个。"; else if (ext?.some((value) => !/^\.[a-z0-9]+$/.test(value))) next.extensions = "扩展名只能包含字母和数字。";
    const max = Number(maxFiles); if (!Number.isInteger(max) || max < 0 || max > 1_000_000) next.maxFiles = "最大文件数必须是 0 到 1000000 的整数。";
    const timeoutNumber = Number(timeout); if (kind === "github_repo" && (!(timeoutNumber > 0) || timeoutNumber > 3600)) next.timeout = "超时必须大于 0 且不超过 3600 秒。";
    if (credentialRef.trim() && !safeCredential(credentialRef.trim())) next.credential = "凭据必须是无查询参数的 secret:// 或 vault:// 引用。";
    setErrors(next); const first = Object.keys(next)[0]; if (first) { queueMicrotask(() => (document.querySelector(`[aria-label="${focusLabels[first]}"]`) as HTMLElement | null)?.focus()); return; }
    const common = { include: includeValues, exclude: excludeValues, extensions: ext, max_files: max, ...(credentialRef.trim() ? { credential_ref: credentialRef.trim() } : {}) };
    const config: LocalDirConfig | GitHubRepoConfig = kind === "local_dir" ? { path: path.trim(), ...common } : { repo: repo.trim(), ref: ref.trim(), ...common, strip_prefix: stripPrefix.trim(), timeout: timeoutNumber, mode };
    const payload = source ? { name: name.trim(), kind, config } : { name: name.trim(), kind, config, metadata: {}, enabled }; if (await onSave(payload)) close();
  };
  const field = (label: string, value: string, setter: (value: string) => void, errorKey: string, options: Record<string, unknown> = {}, multiline = false) => <label className="source-field"><span>{label}</span>{multiline ? <Input.TextArea aria-label={label} name={String(options.name ?? "")} value={value} maxLength={options.maxLength} onChange={(event: { target: { value: string } }) => setter(event.target.value)} autoSize={{ minRows: 2, maxRows: 5 }} /> : <Input aria-label={label} name={String(options.name ?? "")} autoComplete={options.autoComplete ?? "off"} type={options.type} inputMode={options.inputMode} min={options.min} max={options.max} step={options.step} maxLength={options.maxLength} value={value} onChange={(event: { target: { value: string } }) => setter(event.target.value)} />}{errors[errorKey] ? <small role="alert">{errors[errorKey]}</small> : null}</label>;
  return <Modal open={open} title={source ? "编辑来源" : "创建来源"} onCancel={close} onOk={() => void save()} okText={source ? "保存来源" : "创建来源"} cancelText="取消" confirmLoading={saving} className="source-editor-modal"><div className="source-form-grid">{error?.kind === "conflict" ? <div role="alert" className="source-inline-warning">{error.description}</div> : null}{field("来源名称", name, setName, "name", { name: "source-name", autoComplete: "off", maxLength: 128 })}<label className="source-field"><span>连接器类型</span><Select aria-label="连接器类型" value={kind} disabled={saving} options={[{ label: "本地目录", value: "local_dir" }, { label: "GitHub 仓库", value: "github_repo" }]} onChange={(value: SourceKind) => setKind(value)} /></label>{!source ? <label className="source-switch"><Switch checked={enabled} onChange={setEnabled} /><span>创建后立即启用</span></label> : null}{kind === "local_dir" ? field("本地目录", path, setPath, "path", { name: "local-path", maxLength: 2048 }) : <>{field("GitHub 仓库", repo, setRepo, "repo", { name: "github-repo", autoComplete: "off", maxLength: 256 })}{field("Git 引用", ref, setRef, "ref", { name: "github-ref", maxLength: 256 })}{field("Strip prefix", stripPrefix, setStripPrefix, "stripPrefix", { name: "strip-prefix", maxLength: 1024 })}{field("超时（秒）", timeout, setTimeoutValue, "timeout", { name: "timeout", type: "number", inputMode: "decimal", min: 0.01, max: 3600, step: "any" })}<label className="source-field"><span>下载模式</span><Select aria-label="下载模式" value={mode} options={[{ label: "自动", value: "auto" }, { label: "Tarball", value: "tarball" }, { label: "API", value: "api" }]} onChange={(value: "auto" | "tarball" | "api") => setMode(value)} /></label></>}{field("包含规则", include, setInclude, "include", { name: "include-rules" }, true)}{field("排除规则", exclude, setExclude, "exclude", { name: "exclude-rules" }, true)}{field("扩展名", extensionText, setExtensionText, "extensions", { name: "extensions" })}{field("最大文件数", maxFiles, setMaxFiles, "maxFiles", { name: "max-files", type: "number", inputMode: "numeric", min: 0, max: 1_000_000, step: 1 })}{field("凭据引用", credentialRef, setCredentialRef, "credential", { name: "credential-ref", autoComplete: "off", maxLength: 2048 })}<p className="source-safe-note">不接受内联 token、密码或带查询参数的凭据。服务端允许列表是最终判定。</p></div></Modal>;
}
