import { useCallback,useEffect,useRef,useState } from "react";
import { ApiError } from "../../api/client";
import { createDocumentVersion,fetchDocumentVersions } from "../api/governanceApi";
import { projectGovernanceError,type DatasetStatus,type DocumentVersion,type DocumentVersionCreate,type GovernanceErrorView,type GovernanceScope } from "../model/governanceModel";
import type { GovernanceLoadStatus } from "./useDatasetGovernance";
import { useStableGovernanceScope } from "./useStableGovernanceScope";
const aborted=(e:unknown)=>e instanceof ApiError&&e.kind==="aborted";
export function useDocumentVersions(inputScope:GovernanceScope|null,online:boolean|null,datasetStatus:DatasetStatus|null="active"){
 const {scope,key}=useStableGovernanceScope(inputScope);const readable=datasetStatus==="active"||datasetStatus==="archived";const writable=datasetStatus==="active";
 const [status,setStatus]=useState<GovernanceLoadStatus>(!scope?"scope":"ready");const [documentId,setDocumentId]=useState("");const [versions,setVersions]=useState<DocumentVersion[]>([]);const [versionsScopeKey,setVersionsScopeKey]=useState("");const [error,setError]=useState<GovernanceErrorView|null>(null);const [creating,setCreating]=useState(false);const [truncated,setTruncated]=useState(false);
 const keyRef=useRef(key);const epochRef=useRef(0);if(keyRef.current!==key){keyRef.current=key;epochRef.current+=1;}const docRef=useRef("");const loadRef=useRef<AbortController|null>(null);const mutationRef=useRef<AbortController|null>(null);const loadSeq=useRef(0);const current=useCallback((k:string,e:number)=>keyRef.current===k&&epochRef.current===e,[]);
 const load=useCallback(async(raw=docRef.current,preserveError=false)=>{const doc=raw.trim(),s=scope,k=key,e=epochRef.current;if(!s||!readable||online!==true||!doc){if(!doc){docRef.current="";setDocumentId("");}setVersions([]);setVersionsScopeKey("");setTruncated(false);setStatus(!s?"scope":online===false?"offline":"ready");return false;}docRef.current=doc;setDocumentId(doc);loadRef.current?.abort();const c=new AbortController();loadRef.current=c;const seq=++loadSeq.current;setStatus("loading");if(!preserveError)setError(null);try{const r=await fetchDocumentVersions(s,doc,100,{signal:c.signal});if(c.signal.aborted||seq!==loadSeq.current||!current(k,e)||docRef.current!==doc)return false;setVersionsScopeKey(k);setVersions([...r.items].sort((a,b)=>b.revision-a.revision));setTruncated(r.count>=100);setStatus("ready");return true;}catch(x){if(c.signal.aborted||!current(k,e)||aborted(x))return false;setVersions([]);setVersionsScopeKey("");setTruncated(false);setStatus("error");if(!preserveError)setError(projectGovernanceError(x));return false;}},[current,key,online,readable,scope]);
 useEffect(()=>{loadRef.current?.abort();mutationRef.current?.abort();docRef.current="";setDocumentId("");setVersions([]);setVersionsScopeKey("");setTruncated(false);setCreating(false);setError(null);setStatus(!scope?"scope":online===false?"offline":"ready");return()=>{loadRef.current?.abort();mutationRef.current?.abort();};},[key,online,readable,scope]);
 const create=useCallback(async(p:DocumentVersionCreate)=>{const s=scope,k=key,e=epochRef.current,doc=docRef.current;if(!s||!writable||online!==true||!doc||mutationRef.current)return false;const c=new AbortController();mutationRef.current=c;setCreating(true);setError(null);try{await createDocumentVersion(s,doc,p,{signal:c.signal});if(c.signal.aborted||!current(k,e))return false;return await load(doc,false);}catch(x){if(c.signal.aborted||!current(k,e)||aborted(x))return false;const view=projectGovernanceError(x);setError(view);if(view.kind==="conflict")await load(doc,true);return false;}finally{if(mutationRef.current===c)mutationRef.current=null;if(current(k,e))setCreating(false);}},[current,key,load,online,scope,writable]);
 const visible=versionsScopeKey===key; return{status,documentId:visible?documentId:"",versions:visible?versions:[],error,creating,truncated,readOnly:!writable,inspect:(d:string)=>load(d,false),refresh:()=>load(docRef.current,false),create};
}
