import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ApiError } from "../../api/client";
import { addQAAlternative, createQA, deleteQAAlternative, expireQA, fetchQAList, patchQA, restoreQA, reviewQA } from "../api/governanceApi";
import { projectGovernanceError, type DatasetRevisionRequest, type DatasetStatus, type GovernanceErrorView, type GovernanceScope, type QAAlternativeCreate, type QACreate, type QAKnowledge, type QAListFilters, type QAReviewRequest, type QAUpdate } from "../model/governanceModel";
import type { GovernanceLoadStatus } from "./useDatasetGovernance";
import { useStableGovernanceScope } from "./useStableGovernanceScope";
const PAGE_SIZE=10; const aborted=(e:unknown)=>e instanceof ApiError&&e.kind==="aborted";

export function useQAGovernance(inputScope: GovernanceScope|null, online:boolean|null, datasetStatus:DatasetStatus|null="active"){
 const {scope,key}=useStableGovernanceScope(inputScope); const readable=datasetStatus==="active"||datasetStatus==="archived"; const writable=datasetStatus==="active";
 const [status,setStatus]=useState<GovernanceLoadStatus>(!scope?"scope":"loading"); const [items,setItems]=useState<QAKnowledge[]>([]); const [itemsScopeKey,setItemsScopeKey]=useState(""); const [filters,setFilterState]=useState<QAListFilters>({}); const [page,setPageState]=useState(1); const [error,setError]=useState<GovernanceErrorView|null>(null); const [mutatingId,setMutatingId]=useState<string|null>(null); const [truncated,setTruncated]=useState(false);
 const keyRef=useRef(key); const epochRef=useRef(0); if(keyRef.current!==key){keyRef.current=key;epochRef.current+=1;} const loadRef=useRef<AbortController|null>(null); const mutationRef=useRef<AbortController|null>(null); const loadSeq=useRef(0); const busyRef=useRef(false);
 const current=useCallback((k:string,e:number)=>keyRef.current===k&&epochRef.current===e,[]); const requestFilters=useMemo(()=>({...filters,limit:500}),[filters]);
 const load=useCallback(async(preserveError=false)=>{const s=scope,k=key,e=epochRef.current;if(!s||!readable||online!==true){setItems([]);setItemsScopeKey("");setTruncated(false);setStatus(!s?"scope":online===false?"offline":"ready");return false;}loadRef.current?.abort();const c=new AbortController();loadRef.current=c;const seq=++loadSeq.current;setStatus("loading");if(!preserveError)setError(null);try{const r=await fetchQAList(s,requestFilters,{signal:c.signal});if(c.signal.aborted||seq!==loadSeq.current||!current(k,e))return false;setItems(r.items);setItemsScopeKey(k);setTruncated(r.count>=500);setStatus("ready");return true;}catch(x){if(c.signal.aborted||!current(k,e)||aborted(x))return false;setItems([]);setItemsScopeKey("");setTruncated(false);setStatus("error");if(!preserveError)setError(projectGovernanceError(x));return false;}},[current,key,online,readable,requestFilters,scope]);
 useEffect(()=>{loadRef.current?.abort();mutationRef.current?.abort();busyRef.current=false;setMutatingId(null);setItems([]);setItemsScopeKey("");setTruncated(false);setPageState(1);setError(null);void load();return()=>{loadRef.current?.abort();mutationRef.current?.abort();};},[key,online,readable,load]);
 const visibleItems=useMemo(()=>itemsScopeKey===key?items:[],[itemsScopeKey,key,items]); const pageCount=Math.max(1,Math.ceil(visibleItems.length/PAGE_SIZE)); useEffect(()=>setPageState(p=>Math.min(Math.max(1,p),pageCount)),[pageCount]); const pageItems=useMemo(()=>visibleItems.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),[visibleItems,page]);
 const mutate=useCallback(async(id:string,op:(s:GovernanceScope,signal:AbortSignal)=>Promise<unknown>)=>{const s=scope,k=key,e=epochRef.current;if(!s||!writable||online!==true||busyRef.current)return false;const c=new AbortController();mutationRef.current=c;busyRef.current=true;setMutatingId(id);setError(null);try{await op(s,c.signal);if(c.signal.aborted||!current(k,e))return false;return await load(false);}catch(x){if(c.signal.aborted||!current(k,e)||aborted(x))return false;const view=projectGovernanceError(x);setError(view);if(view.kind==="conflict")await load(true);return false;}finally{if(mutationRef.current===c)mutationRef.current=null;if(current(k,e)){busyRef.current=false;setMutatingId(null);}}},[current,key,load,online,scope,writable]);
 const setFilters=useCallback((f:QAListFilters)=>{setPageState(1);setFilterState(f);},[]);
 return {status,items:visibleItems,pageItems,page,pageCount,pageSize:PAGE_SIZE,filters,error,mutatingId,truncated,readOnly:!writable,setPage:(p:number)=>setPageState(Math.max(1,p)),setFilters,refresh:()=>load(false),create:(p:QACreate)=>mutate("create",(s,signal)=>createQA(s,p,{signal})),update:(id:string,p:QAUpdate)=>mutate(id,(s,signal)=>patchQA(s,id,p,{signal})),review:(id:string,p:QAReviewRequest)=>mutate(id,(s,signal)=>reviewQA(s,id,p,{signal})),expire:(id:string,p:DatasetRevisionRequest)=>mutate(id,(s,signal)=>expireQA(s,id,p,{signal})),restore:(id:string,p:DatasetRevisionRequest)=>mutate(id,(s,signal)=>restoreQA(s,id,p,{signal})),addAlternative:(id:string,p:QAAlternativeCreate)=>mutate(id,(s,signal)=>addQAAlternative(s,id,p,{signal})),deleteAlternative:(id:string,a:string,r:number)=>mutate(id,(s,signal)=>deleteQAAlternative(s,id,a,r,{signal}))};
}
