import { useState } from "react";
import { Alert, Button, Drawer, Input, Popconfirm, Tag, Textarea } from "tdesign-react";
import { CopyIcon, DeleteIcon, HistoryIcon, PoweroffIcon, RefreshIcon, RollbackIcon } from "tdesign-icons-react";
import type { UseParseInterventionResult } from "../hooks/useParseIntervention";
import { buildDiff, chunkEditReason, compareChunkToSource, editSourceLabel } from "../model/parseInterventionModel";
export default function ChunkEditorPane({state,onChanged}:{state:UseParseInterventionResult;onChanged?:()=>void}){
 const [view,setView]=useState<"draft"|"source">("draft"),[historyOpen,setHistoryOpen]=useState(false);
 const selected=state.selected;if(!selected)return <section className="parse-pane parse-editor-pane" role="region" aria-label="切片编辑器"><div className="parse-empty">选择一个切片开始检查</div></section>;
 const readOnly=selected.enabled===false||state.authorityMode==="off";const diff=buildDiff(selected.text,state.draft);const source=compareChunkToSource(selected);const tombstoned=selected.enabled===false;const nextEnabled=tombstoned;const toggleLabel=nextEnabled?"启用此切片":"停用此切片";const reasonGiven=state.reason.trim().length>0;const canMutate=reasonGiven&&!state.mutating&&!state.orphanDraft;
 const modeMessage=state.authorityMode==="shadow"?"Shadow 模式会先记录权威 Revision，再同步更新旧 Milvus/图谱投影；同步返回仍不替代一致性检查。":"Active 模式先执行 ChunkHead CAS，再由持久操作异步追赶 Milvus/图谱。";
 const lifecycleMessage=tombstoned?"该切片当前是只读墓碑：不参与检索投影，但内容与 Revision 历史全部保留，可以重新启用。":"该切片当前启用并参与检索投影。停用只写入只读墓碑，数据保留到显式 retention 删除为止。";
 const lines=view==="draft"?diff:source.lines;
 return <section className="parse-pane parse-editor-pane" role="region" aria-label="切片编辑器">
  <div className="parse-pane-heading"><div><span>AUTHORITATIVE EDIT</span><h2>切片编辑器</h2></div><Tag theme={readOnly?"default":"primary"} variant="light">{tombstoned?"墓碑 · 只读":`内容 Revision ${selected.content_revision}`}</Tag></div>
  <div className="parse-cas-grid"><div><span>Chunk ID</span><code>{selected.chunk_id}</code></div><div><span>Expected Revision</span><strong>{state.expectedRevision}</strong></div><div><span>Document Revision</span><strong>{selected.document_revision??"未提供"}</strong></div><div><span>Projection Fence</span><strong>{selected.desired_index_revision??selected.content_revision}</strong></div><div><span>最后人工写入</span><strong>{editSourceLabel(selected.edit_source)} · {selected.editor_id||"未记录"}</strong></div></div>
  <div className="parse-lifecycle"><div><span>切片生命周期</span><p>{lifecycleMessage}</p></div><Popconfirm theme={tombstoned?"default":"danger"} content={tombstoned?"启用会从墓碑恢复该切片，并先写入一条不可变 Revision；原因记在 ChunkHead 上。":"停用会写入只读墓碑并新建一条 Revision；内容保留，但不再参与检索投影。"} confirmBtn={{content:toggleLabel,theme:tombstoned?"primary":"danger"}} onConfirm={()=>void state.setEnabled(nextEnabled).then(ok=>{if(ok)onChanged?.();})}><Button tag="button" theme={tombstoned?"primary":"warning"} variant={tombstoned?"base":"outline"} icon={<PoweroffIcon/>} disabled={!canMutate} aria-label={toggleLabel}>{toggleLabel}</Button></Popconfirm></div>
  {!reasonGiven?<p className="parse-muted">启用、停用、提交与回滚都要求先填写修改原因；原因随写入记在 ChunkHead 的 chunk_metadata 上。</p>:null}
  <label className="parse-editor-field"><span>当前内容</span><Textarea aria-label="切片正文" value={state.draft} disabled={readOnly} onChange={v=>state.setDraft(String(v))} autosize={{minRows:12,maxRows:24}}/></label>
  <label className="parse-editor-field"><span>修改原因</span><Input aria-label="修改原因" value={state.reason} disabled={readOnly} onChange={v=>state.setReason(String(v))} placeholder="例如：修正 OCR 错字或恢复遗漏条款"/>{chunkEditReason(selected)?<span className="parse-muted">上一次写入的原因：{chunkEditReason(selected)}</span>:null}</label>
  <Alert theme="info" title="原因记在 ChunkHead，不逐版保存" message="编辑、启用与回滚的原因会写入 ChunkHead 的 chunk_metadata；Revision 历史里每一版只有内容、编辑者与时间，这里不会把它伪装成逐版审计。"/><Alert theme="warning" title="投影影响" message={modeMessage}/>
  <div className="parse-editor-secondary"><Button variant="text" icon={<CopyIcon/>} onClick={()=>void navigator.clipboard?.writeText(state.draft)}>复制正文</Button><Button tag="button" variant="text" icon={<RefreshIcon/>} disabled={readOnly} onClick={state.resetDraft}>重置草稿</Button><Button variant="text" icon={<HistoryIcon/>} onClick={()=>{setHistoryOpen(true);void state.ensureRevisions();}}>Revision 历史</Button><Popconfirm theme="danger" content="删除会写入只读墓碑。" confirmBtn={{content:"写入墓碑",theme:"danger"}} onConfirm={()=>void state.removeSelected().then(ok=>{if(ok)onChanged?.();})}><Button tag="button" variant="text" theme="danger" disabled={readOnly} icon={<DeleteIcon/>}>删除切片</Button></Popconfirm></div>
  <div className="parse-section-heading"><h3>{view==="draft"?"修改 Diff":"原始 vs 当前"}</h3><span>{view==="draft"?(state.dirty?"待提交":"没有内容变更"):(source.available?(source.changed?`人工改过 ${source.removed} 行原始内容，新增 ${source.added} 行`:"当前内容与解析器产出一致"):"原始内容未加载")}</span></div>
  <div className="parse-view-toggle" role="group" aria-label="差异视图切换"><Button size="small" variant={view==="draft"?"base":"text"} aria-pressed={view==="draft"} onClick={()=>setView("draft")}>草稿 Diff</Button><Button size="small" variant={view==="source"?"base":"text"} aria-pressed={view==="source"} onClick={()=>{setView("source");if(source.available===false)void state.refreshSelectedDetail();}}>原始 vs 当前</Button></div>
  {view==="source"&&!source.available?<div className="parse-empty">{state.detailLoading?"正在读取切片详情…":"服务端未随列表返回原始内容（source_content 只在单切片读取里给出）。"}<Button tag="button" size="small" variant="outline" loading={state.detailLoading} disabled={state.authorityMode==="off"} onClick={()=>void state.refreshSelectedDetail()}>读取原始内容</Button></div>:null}
  <div className="parse-diff" role="region" tabIndex={0} aria-label={view==="draft"?"修改差异预览":"原始与当前内容对比"}>{lines.map((l,i)=><div key={`${l.kind}-${i}`} className={`is-${l.kind}`}><b>{l.kind==="add"?"+":l.kind==="remove"?"−":" "}</b><code>{l.text||" "}</code></div>)}</div>
  {state.orphanDraft?<div className="parse-conflict" role="alert"><h3>{state.orphanDraft.resolution==="conflict"?"Revision 冲突":state.orphanDraft.resolution==="tombstone"?"切片已成为墓碑":"切片已不存在"}</h3><p>本地草稿与原因已独立保留，不会随分页、搜索或选择变化丢失。</p><div className="parse-conflict-columns"><div><span>服务器状态</span><pre>{state.orphanDraft.server?.text??"资源不可用"}</pre></div><div><span>我的草稿</span><pre>{state.orphanDraft.draft}</pre></div></div><div><Button variant="outline" onClick={()=>void navigator.clipboard?.writeText(state.orphanDraft!.draft)}>复制草稿</Button><Button variant="text" onClick={state.discardOrphanDraft}>丢弃草稿</Button>{state.canRebaseOrphan?<Button theme="warning" onClick={state.rebaseOrphanDraft}>基于新 Revision 继续修改</Button>:null}</div></div>:null}
  <Drawer className="parse-history-drawer" header={`切片 Revision 历史 · ${selected.chunk_id}`} placement="right" size="small" visible={historyOpen} onClose={()=>setHistoryOpen(false)} destroyOnClose>
   <div className="parse-history-toolbar"><span>{state.revisionsLoading?"正在读取不可变 Revision…":state.revisionsReady?`共 ${state.revisions.length} 条不可变快照`:"尚未读取"}</span><Button size="small" variant="text" icon={<RefreshIcon/>} loading={state.revisionsLoading} onClick={()=>void state.loadRevisions()}>重新读取</Button></div>
   {state.revisionsError?<Alert theme="error" title="无法读取 Revision 历史" message={state.revisionsError}/>:null}
   {!state.revisionsLoading&&!state.revisionsError&&state.revisionsReady&&!state.revisions.length?<div className="parse-empty">这个切片还没有不可变 Revision 快照；每次人工编辑、启停或回滚都会先留存一版再改 ChunkHead。</div>:null}
   <ol className="parse-history-list">{state.revisions.map(row=><li key={row.revision} className={row.isCurrent?"is-current":""}><div className="parse-history-row-top"><strong>Revision {row.revision}</strong><Tag theme={row.isCurrent?"primary":"default"} variant="light">{row.isCurrent?"当前内容":"历史快照"}</Tag><Tag theme={row.enabled?"success":"default"} variant="light">{row.enabled?"启用":"墓碑"}</Tag></div><div className="parse-history-row-facts"><span>{row.editedAt}</span><span>{row.editSourceLabel}</span><span>{row.editorId||"编辑者未记录"}</span></div><pre>{row.content}</pre>{row.canRevertTo?<Popconfirm theme="warning" content={tombstoned?"回滚要求切片先脱离墓碑只读状态：请先启用此切片。":`会把 Revision ${row.revision} 的内容作为新的 Revision 写回 ChunkHead，不会改写历史。`} confirmBtn={{content:"回滚到此版",theme:"warning"}} onConfirm={()=>void state.revertTo(row.revision).then(ok=>{if(ok){onChanged?.();setHistoryOpen(false);}})}><Button tag="button" size="small" variant="outline" icon={<RollbackIcon/>} disabled={!canMutate||tombstoned} aria-label={`回滚切片到 Revision ${row.revision}`}>回滚到此版</Button></Popconfirm>:null}</li>)}</ol>
  </Drawer>
 </section>;
}
