import { useMemo, useState } from "react";
import { Button, Input, Select, Switch, Tag } from "tdesign-react";
import type { DocumentChunkItem } from "../../types/rag";
import type { ParseFilters } from "../hooks/useParseIntervention";
import { chunkWarnings, estimateTokens, projectChunkLifecycle, projectProjectionLifecycle } from "../model/parseInterventionModel";
import ChunkMergedView from "./ChunkMergedView";
const ROW=126,HEIGHT=560,OVER=3;
export default function ChunkListPane(p:{chunks:DocumentChunkItem[];total:number;selectedId:string;query:string;filters:ParseFilters;knownParents:Set<string>;missingParents:Set<string>;hasMore:boolean;loadingMore:boolean;onQueryChange:(v:string)=>void;onFiltersChange:(v:ParseFilters)=>void;onSelect:(id:string)=>void;onLoadMore:()=>void}){
 const [top,setTop]=useState(0);const [view,setView]=useState<"list"|"merged">("list");const visible=useMemo(()=>p.chunks.filter(c=>{const life=projectChunkLifecycle(c),proj=projectProjectionLifecycle(c).state,rel=c.parent_chunk_id||c.chunk_role==="child"?"child":"flat";return(p.filters.lifecycle==="all"||p.filters.lifecycle===life)&&(p.filters.lifecycle!=="all"||p.filters.showTombstones||life!=="tombstone")&&(p.filters.projection==="all"||p.filters.projection===proj)&&(p.filters.relation==="all"||p.filters.relation===rel)&&(!p.filters.warningsOnly||chunkWarnings(c,p.knownParents,p.missingParents).length>0);}),[p.chunks,p.filters,p.knownParents,p.missingParents]);
 const tombstones=p.chunks.filter(x=>projectChunkLifecycle(x)==="tombstone").length;const active=Math.max(0,visible.findIndex(x=>x.chunk_id===p.selectedId));let start=Math.max(0,Math.floor(top/ROW)-OVER);const count=Math.ceil(HEIGHT/ROW)+OVER*2;if(active<start||active>=start+count)start=Math.max(0,active-Math.floor(count/2));const windowed=visible.slice(start,start+count);const move=(d:number|"home"|"end")=>{if(!visible.length)return;const i=d==="home"?0:d==="end"?visible.length-1:Math.max(0,Math.min(visible.length-1,active+d));p.onSelect(visible[i].chunk_id);};
 const viewSwitch=<div className="parse-view-switch" role="group" aria-label="切片视图模式"><Button variant={view==="list"?"base":"text"} aria-pressed={view==="list"} onClick={()=>setView("list")}>切片列表</Button><Button variant={view==="merged"?"base":"text"} aria-pressed={view==="merged"} onClick={()=>setView("merged")}>整篇合并</Button></div>;
 if(view==="merged")return <ChunkMergedView chunks={p.chunks} total={p.query.trim()?null:p.total} query={p.query.trim()} selectedId={p.selectedId} hasMore={p.hasMore} loadingMore={p.loadingMore} onLoadMore={p.onLoadMore} onSelect={p.onSelect} headerExtra={viewSwitch}/>;
 return <section className="parse-pane parse-list-pane" role="region" aria-label="切片列表"><div className="parse-pane-heading"><div><span>CHUNK HEADS</span><h2>切片列表</h2></div><Tag variant="light">已加载 {p.chunks.length} / {p.total}</Tag>{viewSwitch}</div><Input value={p.query} onChange={v=>p.onQueryChange(String(v))} aria-label="搜索切片" placeholder="服务端搜索 ID、标题、正文或上下文"/><div className="parse-filter-grid"><Select value={p.filters.lifecycle} options={[{value:"all",label:"全部状态"},{value:"enabled",label:"已启用"},{value:"tombstone",label:"墓碑"}]} onChange={v=>p.onFiltersChange({...p.filters,lifecycle:String(v) as ParseFilters["lifecycle"]})}/><label className="parse-warning-toggle"><Switch value={p.filters.warningsOnly} onChange={v=>p.onFiltersChange({...p.filters,warningsOnly:Boolean(v)})}/><span>只看警告</span></label><label className="parse-warning-toggle"><Switch value={p.filters.showTombstones} onChange={v=>p.onFiltersChange({...p.filters,showTombstones:Boolean(v)})}/><span>{`显示墓碑（${tombstones}）`}</span></label></div><div className="parse-chunk-scroll" role="listbox" aria-label="文档切片" tabIndex={0} aria-activedescendant={visible[active]?`parse-chunk-${visible[active].chunk_id}`:undefined} onScroll={e=>setTop(e.currentTarget.scrollTop)} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();move(1)}else if(e.key==="ArrowUp"){e.preventDefault();move(-1)}else if(e.key==="Home"){e.preventDefault();move("home")}else if(e.key==="End"){e.preventDefault();move("end")}}}><div className="parse-chunk-spacer" style={{height:visible.length*ROW}}><div style={{transform:`translateY(${start*ROW}px)`}}>{windowed.map(c=>{const proj=projectProjectionLifecycle(c),warn=chunkWarnings(c,p.knownParents,p.missingParents);return <div role="option" aria-selected={c.chunk_id===p.selectedId} id={`parse-chunk-${c.chunk_id}`} key={c.chunk_id} className={c.chunk_id===p.selectedId?"parse-chunk-row is-selected":"parse-chunk-row"} onMouseDown={e=>{e.preventDefault();p.onSelect(c.chunk_id)}}><div className="parse-chunk-row-top"><strong>#{c.seq+1} {c.heading||"未命名切片"}</strong><Tag>{c.enabled===false?"墓碑":"启用"}</Tag></div><p>{c.text.slice(0,94)}</p><div className="parse-chunk-row-facts"><span>内容 R{c.content_revision}</span><span>{c.char_count} 字符 / 约 {c.token_estimate??estimateTokens(c.text)} tokens</span></div><div className="parse-chunk-row-bottom"><Tag>{proj.label}</Tag>{warn.length?<b>{warn.length} 项警告</b>:null}</div></div>})}</div></div></div>{p.hasMore?<Button block variant="outline" loading={p.loadingMore} onClick={p.onLoadMore}>加载更多（{p.chunks.length} / {p.total}）</Button>:null}</section>;
}
