/**
 * 演示数据 —— 桥服务离线时的兜底。
 *
 * 展示 RAG4C 的完整结果形态：带 [N] 引用标记的答案、三层引用验证状态、
 * 证据片段、弃权提示与链路追踪流水，方便在无模型 / 无 Milvus 环境下预览 UI。
 */
import type {
  ConfigSnapshot,
  DocumentItem,
  EvalReport,
  GraphSubgraph,
  HealthInfo,
  MetricsSnapshot,
  QueryResponse,
} from "../types/rag";

const DEMO_TRACES = [
  "[gate] 查询进入复杂度门控：判定为简单查询，跳过改写与意图路由（零 LLM 成本）",
  "[router] 路由决策: target=hybrid, confidence=0.87, degraded=false",
  "[retrieval] 混合检索: 稠密向量 (BGE-M3) + 稀疏 BM25 (Milvus Function)，RRF 融合",
  "[retrieval] 命中 3 个 chunk，BGE-reranker-v2-M3 重排后保留 top-3",
  "[generation] 生成答案，强制 [N] 引用标记，越界编号自动剥离",
  "[verify/L1] 引用存在性检查: 3/3 通过",
  "[verify/L2] 文本哈希校验: 3/3 一致",
  "[verify/L3] 蕴含判定 (LLM): 3/3 支撑",
  "[abstention] 双阈值判定: 检索分数 0.62 >= 0.55，蕴含分数 0.94 >= 0.75，不弃权",
  "[done] 返回 QueryResult（route=hybrid, abstained=false）",
];

const DEMO_QUERY_RESPONSE: QueryResponse = {
  result: {
    query: "公司的报销流程是什么？",
    answer:
      "公司的报销流程分为四步：1) 员工在 OA 系统提交费用报销单，附上发票与审批链[1]；2) 直属主管在 3 个工作日内完成一级审批，超时自动提醒[2]；3) 财务部门在 5 个工作日内完成凭证审核，重点核对发票真伪与预算科目[1]；4) 审批通过后由出纳统一发起银行转账，款项通常在 T+2 到账[3]。",
    citations: [
      {
        claim: "员工在 OA 系统提交费用报销单，附上发票与审批链",
        chunk_id: "chunk-a1f3e9",
        status: "ok",
        reason: "L1 存在 / L2 哈希一致 / L3 蕴含判定通过",
      },
      {
        claim: "直属主管在 3 个工作日内完成一级审批，超时自动提醒",
        chunk_id: "chunk-b2c8d1",
        status: "ok",
        reason: "L1 存在 / L2 哈希一致 / L3 蕴含判定通过",
      },
      {
        claim: "财务部门在 5 个工作日内完成凭证审核，重点核对发票真伪与预算科目",
        chunk_id: "chunk-a1f3e9",
        status: "exists_only",
        reason: "证据存在但仅部分支撑（原文未明确提及预算科目核对）",
      },
      {
        claim: "款项通常在 T+2 到账",
        chunk_id: "chunk-c4d0e2",
        status: "ok",
        reason: "L1 存在 / L2 哈希一致 / L3 蕴含判定通过",
      },
    ],
    verdict: { evidence_chunks: 3 },
    abstained: false,
    route: "hybrid",
    traces: DEMO_TRACES,
    evidence: [
      {
        chunk_id: "chunk-a1f3e9",
        doc_id: "doc-hr-001",
        text: "员工报销：登录 OA 系统「费用报销」模块，填写报销单并上传发票原件扫描件，提交后流转至直属主管审批。财务部负责凭证审核，核对发票真伪、金额与预算科目是否一致，审核周期为 5 个工作日。",
        score: 0.68,
        rank: 1,
        source: "hr",
      },
      {
        chunk_id: "chunk-b2c8d1",
        doc_id: "doc-hr-001",
        text: "一级审批：直属主管应在收到报销单后 3 个工作日内完成审批；超时系统自动发送提醒。审批意见包括同意、驳回与退回修改三种状态。",
        score: 0.61,
        rank: 2,
        source: "hr",
      },
      {
        chunk_id: "chunk-c4d0e2",
        doc_id: "doc-fin-002",
        text: "付款时效：审批通过后由出纳统一发起银行转账，常规报销款项在审批完成后 T+2 个工作日内到账；紧急报销可申请加急通道。",
        score: 0.55,
        rank: 3,
        source: "fin",
      },
    ],
  },
  using_mock: true,
  duration_ms: 1240,
};

const DEMO_ABSTAIN_RESPONSE: QueryResponse = {
  result: {
    query: "去年 Q4 的毛利率是多少？",
    answer: "",
    citations: [],
    verdict: { evidence_chunks: 0 },
    abstained: true,
    route: "hybrid",
    traces: [
      "[router] 路由决策: target=hybrid, confidence=0.52, degraded=false",
      "[retrieval] 混合检索完成，最高分 0.31",
      "[abstention] 弃权: 检索分数 0.31 < 阈值 0.55，知识库无相关内容，拒绝作答",
      "[done] 返回弃权结果（abstained=true, answer=''）",
    ],
  },
  using_mock: true,
  duration_ms: 860,
};

export const DEMO_HEALTH: HealthInfo = {
  status: "degraded",
  milvus_uri: "http://localhost:19530 (Milvus server)",
  embedding_model: "BAAI/bge-m3",
  reranker_model: "BAAI/bge-reranker-v2-m3",
  generation_model: "qwen2.5 (Ollama)",
  graph_engine_on: true,
};

/** 演示模式的问题 -> 结果映射 */
export const DEMO_RESPONSES: Record<string, QueryResponse> = {
  "公司的报销流程是什么？": DEMO_QUERY_RESPONSE,
  "去年 Q4 的毛利率是多少？": DEMO_ABSTAIN_RESPONSE,
  "员工年假制度是怎么规定的？": DEMO_ABSTAIN_RESPONSE,
  "入职需要准备哪些材料？": DEMO_QUERY_RESPONSE,
};

/* ===================== 监控页演示数据 ===================== */

export const DEMO_METRICS: MetricsSnapshot = {
  ts: "2026-08-06 19:50:00",
  uptime_s: 8420,
  circuits: {
    retrieval: { state: "closed", failures: 0, open_count: 0, close_count: 0 },
    "llm.generation": { state: "closed", failures: 1, open_count: 2, close_count: 2 },
  },
  metrics: {
    "query.total": {
      count: 128,
      sum: 89240,
      mean: 697.2,
      min: 412,
      max: 1834,
      p50: 641,
      p95: 1292,
      p99: 1687,
    },
    "query.total.errors": {
      count: 3,
      sum: 0,
      mean: 0,
      min: 0,
      max: 0,
      p50: 0,
      p95: 0,
      p99: 0,
      error_rate: 0.0234,
    },
    "query.abstained": {
      count: 19,
      sum: 0,
      mean: 0,
      min: 0,
      max: 0,
      p50: 0,
      p95: 0,
      p99: 0,
    },
    "span.search": {
      count: 128,
      sum: 26112,
      mean: 204.0,
      min: 96,
      max: 611,
      p50: 178,
      p95: 402,
      p99: 540,
    },
    "span.rerank": {
      count: 128,
      sum: 12800,
      mean: 100.0,
      min: 48,
      max: 320,
      p50: 92,
      p95: 210,
      p99: 290,
    },
    "span.generate": {
      count: 124,
      sum: 44786,
      mean: 361.2,
      min: 188,
      max: 890,
      p50: 342,
      p95: 610,
      p99: 780,
    },
    "span.verify": {
      count: 124,
      sum: 15872,
      mean: 128.0,
      min: 42,
      max: 365,
      p50: 112,
      p95: 260,
      p99: 330,
    },
    "span.verify_l3": {
      count: 124,
      sum: 13020,
      mean: 105.0,
      min: 36,
      max: 300,
      p50: 96,
      p95: 218,
      p99: 280,
    },
    "span.embed": {
      count: 128,
      sum: 5120,
      mean: 40.0,
      min: 18,
      max: 120,
      p50: 36,
      p95: 88,
      p99: 110,
    },
    "http.query.cached": {
      count: 22,
      sum: 0,
      mean: 0,
      min: 0,
      max: 0,
      p50: 0,
      p95: 0,
      p99: 0,
    },
  },
  recent_queries: [
    {
      query: "公司的报销流程是什么？",
      route: "hybrid",
      abstained: false,
      duration_ms: 1186,
      citations: 4,
      traces: DEMO_TRACES,
      ts: "2026-08-16 19:49:21",
    },
    {
      query: "谁在什么时间发明了什么？",
      route: "vector_graph_rag",
      abstained: false,
      duration_ms: 1542,
      citations: 3,
      traces: [
        "[router] 路由决策: target=vector_graph_rag, confidence=0.63, degraded=false",
        "[retrieval] 混合检索完成（候选 6 条）",
        "[graph] 实体检索命中 2 个实体，子图扩展 1 跳，关系候选 5 条",
        "[graph] LLM 重排完成，保留 top-3 关系，合并 2 条 passage",
        "[generation] 生成答案，引用标记 [1][2][3]",
        "[verify] 三层验证 3/3 通过",
      ],
      ts: "2026-08-16 19:47:02",
    },
    {
      query: "去年 Q4 的毛利率是多少？",
      route: "hybrid",
      abstained: true,
      duration_ms: 860,
      citations: 0,
      traces: [
        "[retrieval] 混合检索完成，最高分 0.31",
        "[abstention] 弃权: 检索分数 0.31 < 阈值 0.55",
      ],
      ts: "2026-08-16 19:45:37",
    },
  ],
};

/* ===================== 图谱可视化演示数据 ===================== */

export const DEMO_GRAPH: GraphSubgraph = {
  entities: [
    {
      id: "ent-turing",
      text: "图灵",
      score: 0.92,
      relation_ids: ["rel-1", "rel-2", "rel-3", "rel-6"],
      passage_ids: ["chunk-a1"],
    },
    {
      id: "ent-enigma",
      text: "恩尼格玛密码机",
      score: 0.87,
      relation_ids: ["rel-1", "rel-4"],
      passage_ids: ["chunk-a1", "chunk-a2"],
    },
    {
      id: "ent-1939",
      text: "1939年",
      score: 0.81,
      relation_ids: ["rel-4"],
      passage_ids: ["chunk-a2"],
    },
    {
      id: "ent-bombe",
      text: "炸弹机",
      score: 0.78,
      relation_ids: ["rel-3", "rel-5"],
      passage_ids: ["chunk-a3"],
    },
    {
      id: "ent-bletchley",
      text: "布莱切利园",
      score: 0.72,
      relation_ids: ["rel-2", "rel-5"],
      passage_ids: ["chunk-a3"],
    },
    {
      id: "ent-computing",
      text: "计算科学",
      score: 0.66,
      relation_ids: ["rel-6"],
      passage_ids: ["chunk-a4"],
    },
  ],
  relations: [
    {
      id: "rel-1",
      text: "图灵 破解 恩尼格玛密码机",
      entity_ids: ["ent-turing", "ent-enigma"],
      subject: "图灵",
      predicate: "破解",
      object: "恩尼格玛密码机",
      score: 0.9,
    },
    {
      id: "rel-2",
      text: "图灵 就职于 布莱切利园",
      entity_ids: ["ent-turing", "ent-bletchley"],
      subject: "图灵",
      predicate: "就职于",
      object: "布莱切利园",
      score: 0.85,
    },
    {
      id: "rel-3",
      text: "图灵 发明 炸弹机",
      entity_ids: ["ent-turing", "ent-bombe"],
      subject: "图灵",
      predicate: "发明",
      object: "炸弹机",
      score: 0.82,
    },
    {
      id: "rel-4",
      text: "恩尼格玛密码机 出现在 1939年",
      entity_ids: ["ent-enigma", "ent-1939"],
      subject: "恩尼格玛密码机",
      predicate: "出现在",
      object: "1939年",
      score: 0.74,
    },
    {
      id: "rel-5",
      text: "炸弹机 部署于 布莱切利园",
      entity_ids: ["ent-bombe", "ent-bletchley"],
      subject: "炸弹机",
      predicate: "部署于",
      object: "布莱切利园",
      score: 0.7,
    },
    {
      id: "rel-6",
      text: "图灵 奠基 计算科学",
      entity_ids: ["ent-turing", "ent-computing"],
      subject: "图灵",
      predicate: "奠基",
      object: "计算科学",
      score: 0.65,
    },
  ],
};

/* ===================== 评测页演示数据 ===================== */

export const DEMO_EVAL_REPORT: EvalReport = {
  metrics: {
    refusal_rate: 0.25,
    over_refusal_rate: 0.1667,
    hallucination_rate: 0.0,
    avg_groundedness: 0.86,
    avg_relevance: 0.78,
    citation_failure_rate: 0.05,
  },
  cases: [
    {
      id: "milvus_index_types",
      question: "Milvus 支持哪些索引类型？HNSW 和 IVF 有什么区别？",
      unanswerable: false,
      abstained: false,
      answered: true,
      groundedness: 0.9,
      relevance: 0.85,
      citations_ok: true,
      notes: "",
    },
    {
      id: "hybrid_search_rrf",
      question: "混合检索里的 RRF 是如何融合稠密与稀疏结果的？",
      unanswerable: false,
      abstained: false,
      answered: true,
      groundedness: 0.88,
      relevance: 0.8,
      citations_ok: true,
      notes: "",
    },
    {
      id: "milvus_lite_deploy",
      question: "Milvus Lite 如何零部署使用？",
      unanswerable: false,
      abstained: false,
      answered: true,
      groundedness: 0.82,
      relevance: 0.75,
      citations_ok: true,
      notes: "",
    },
    {
      id: "policy_annual_leave",
      question: "云帆科技的员工年假是怎么规定的？",
      unanswerable: false,
      abstained: false,
      answered: true,
      groundedness: 0.85,
      relevance: 0.82,
      citations_ok: false,
      notes: "1 条引用为弱支撑",
    },
    {
      id: "unanswerable_1",
      question: "去年 Q4 的毛利率是多少？",
      unanswerable: true,
      abstained: true,
      answered: false,
      groundedness: null,
      relevance: null,
      citations_ok: true,
      notes: "正确拒答",
    },
    {
      id: "unanswerable_2",
      question: "公司的 2025 年战略规划细节？",
      unanswerable: true,
      abstained: true,
      answered: false,
      groundedness: null,
      relevance: null,
      citations_ok: true,
      notes: "正确拒答",
    },
    {
      id: "unanswerable_3",
      question: "CEO 的个人履历？",
      unanswerable: true,
      abstained: true,
      answered: false,
      groundedness: null,
      relevance: null,
      citations_ok: true,
      notes: "正确拒答",
    },
    {
      id: "ambiguous_1",
      question: "介绍一下公司的报销与采购流程",
      unanswerable: false,
      abstained: true,
      answered: false,
      groundedness: null,
      relevance: null,
      citations_ok: true,
      notes: "过度拒答（可答被拒）",
    },
  ],
};

export const DEMO_DATASETS: string[] = [
  "eval/dataset_sample.py:SAMPLE_DATASET",
  "eval/dataset_advanced.py:SAMPLE_DATASET",
];

/* ===================== 文档管理页演示数据 ===================== */

/** 覆盖状态机的各个阶段，便于离线预览状态标签与进度条 */
export const DEMO_DOCUMENTS: DocumentItem[] = [
  {
    id: "doc-hr-001",
    name: "员工手册-2026版.pdf",
    status: "completed",
    progress: 1,
    chunk_count: 142,
    doc_type: "pdf",
    error_message: "",
  },
  {
    id: "doc-fin-002",
    name: "财务报销管理制度.docx",
    status: "completed",
    progress: 1,
    chunk_count: 68,
    doc_type: "word",
    error_message: "",
  },
  {
    id: "doc-prd-003",
    name: "产品需求文档-V3.md",
    status: "indexing",
    progress: 0.72,
    chunk_count: 0,
    doc_type: "markdown",
    error_message: "",
  },
  {
    id: "doc-ops-004",
    name: "2025年度经营数据.xlsx",
    status: "splitting",
    progress: 0.35,
    chunk_count: 0,
    doc_type: "excel",
    error_message: "",
  },
  {
    id: "doc-legal-005",
    name: "供应商合同模板.pdf",
    status: "waiting",
    progress: 0,
    chunk_count: 0,
    doc_type: "pdf",
    error_message: "",
  },
  {
    id: "doc-arch-006",
    name: "系统架构说明-扫描件.pdf",
    status: "error",
    progress: 0.18,
    chunk_count: 0,
    doc_type: "pdf",
    error_message: "解析失败：MinerU 未配置 API Token，扫描件需要 OCR 引擎",
  },
];

/* ===================== 配置中心演示数据 ===================== */

const CF = (
  path: string,
  value: unknown,
  type: string,
  source: "env" | "default" = "default",
  sensitive = false,
  hint = "",
) => ({
  path,
  env: `RAG4C_${path.toUpperCase().replace(/\./g, "_")}`,
  value,
  type,
  source,
  sensitive,
  hint,
});

export const DEMO_CONFIG: ConfigSnapshot = {
  ts: "2026-08-06 20:00:00",
  sections: {
    milvus: {
      label: "Milvus 向量库",
      description: "URI / 集合名 / HNSW 索引与混合检索参数；uri 为本地路径即 Milvus Lite",
      fields: [
        CF("milvus.uri", "./rag4c.db", "str", "env"),
        CF("milvus.collection_name", "rag4c_chunks", "str"),
        CF("milvus.entity_collection", "rag4c_entities", "str"),
        CF("milvus.relation_collection", "rag4c_relations", "str"),
        CF("milvus.dim", 1024, "int"),
        CF("milvus.index_type", "HNSW", "str"),
        CF("milvus.metric_type", "COSINE", "str"),
        CF("milvus.nlist", 1024, "int"),
        CF("milvus.ef_construction", 200, "int"),
        CF("milvus.nprobe", 16, "int"),
        CF("milvus.ef", 64, "int"),
        CF("milvus.bm25_k1", 1.2, "float"),
        CF("milvus.bm25_b", 0.75, "float"),
        CF("milvus.sparse_index_algo", "DAAT_MAXSCORE", "str", "default", false, "稀疏倒排索引算法：BM25 度量默认 DAAT_MAXSCORE"),
        CF("milvus.candidate_factor", 4, "int"),
        CF("milvus.rrf_k", 60, "int"),
        CF("milvus.timeout", 30.0, "float"),      ],
    },
    embedding: {
      label: "嵌入服务",
      description: "provider=api（SiliconFlow）或 local（FlagEmbedding BGE-M3）",
      fields: [
        CF("embedding.provider", "api", "str", "env"),
        CF("embedding.model", "BAAI/bge-m3", "str"),
        CF("embedding.max_length", 8192, "int"),
        CF("embedding.batch_size", 32, "int"),
        CF("embedding.normalize_embeddings", false, "bool"),
        CF("embedding.api_base_url", "https://api.siliconflow.cn/v1", "str", "env"),
        CF("embedding.api_key", "", "str", "default", true),
        CF("embedding.api_timeout", 120.0, "float"),
      ],
    },
    reranker: {
      label: "重排序",
      description: "BGE-reranker-v2-M3 本地模型参数",
      fields: [
        CF("reranker.model", "BAAI/bge-reranker-v2-m3", "str"),
        CF("reranker.device", "cpu", "str"),
        CF("reranker.use_fp16", false, "bool"),
        CF("reranker.batch_size", 32, "int"),
        CF("reranker.normalize_score", true, "bool"),
      ],
    },
    llm: {
      label: "LLM 槽位",
      description: "9 个业务槽位：改写 / 路由 / 生成 / 裁判 / 三元组 / 查询增强等，OpenAI 兼容端点",
      fields: [
        CF("llm.generation.base_url", "http://localhost:11434/v1", "str", "env"),
        CF("llm.generation.model", "qwen2.5", "str"),
        CF("llm.generation.temperature", 0.7, "float"),
        CF("llm.generation.max_tokens", 4096, "int"),
        CF("llm.judge.model", "qwen2.5", "str"),
        CF("llm.judge.temperature", 0.0, "float"),
        CF("llm.router_llm.model", "qwen2.5", "str"),
        CF("llm.rewrite.model", "qwen2.5", "str"),
        CF("llm.triplet.model", "qwen2.5", "str"),
      ],
    },
    pipeline: {
      label: "检索管线",
      description: "混合检索 / 重排 / 图谱 / ACL 开关、来源多样性、弃权双阈值、增强开关、图编排",
      fields: [
        CF("pipeline.hybrid_search_on", true, "bool"),
        CF("pipeline.rerank_on", true, "bool"),
        CF("pipeline.graph_retrieval_on", true, "bool", "env"),
        CF("pipeline.acl_filter_on", true, "bool"),
        CF("pipeline.source_diversity", "off", "str"),
        CF("pipeline.group_size", 3, "int"),
        CF("pipeline.group_by_field", "doc_id", "str"),
        CF("pipeline.mmr_lambda", 0.7, "float"),
        CF("pipeline.complexity_gate_on", true, "bool"),
        CF("pipeline.retrieval_score_threshold", 0.3, "float"),
        CF("pipeline.entailment_score_threshold", 0.6, "float"),
        CF("pipeline.top_k", 8, "int"),
        CF("pipeline.hyde_on", false, "bool"),
        CF("pipeline.subqueries_on", false, "bool"),
        CF("pipeline.stepback_on", false, "bool"),
        CF("pipeline.sentence_window_on", false, "bool"),
        CF("pipeline.enhance_candidate_k", 8, "int", "default", false, "查询增强检索的候选数量"),
        CF("pipeline.graph_engine_on", true, "bool"),
        CF("pipeline.clean_on", true, "bool", "default", false, "入库清洗：切分前剥离页码、版权行、裸 URL 与控制字符等噪声"),
        CF("pipeline.contextual_on", false, "bool", "default", false, "Contextual Retrieval：入库时为每个片段生成文档级定位上下文，拼在正文前一起向量化"),
        CF("pipeline.graph_index_on", false, "bool", "default", false, "入库期构建知识图谱：抽取三元组并向量化实体与关系；检索侧「图谱辅助检索」依赖本开关"),
        CF("pipeline.chunking_mode", "auto", "str", "default", false, "文档切分方式：auto 自动判定，recursive 按固定长度，parent_child 按章节结构，qa 表格逐行转问答"),
        CF("pipeline.simple_doc_max_chars", 4000, "int", "default", false, "短文档阈值：低于该字数的文档按固定长度切分（auto 模式生效）"),
      ],
    },
    graph: {
      label: "知识图谱检索",      description: "vector-graph-rag：实体/关系 top-k、相似度阈值、子图扩展跳数、LLM 重排",
      fields: [
        CF("graph.entity_top_k", 20, "int"),
        CF("graph.relation_top_k", 20, "int"),
        CF("graph.entity_similarity_threshold", 0.9, "float"),
        CF("graph.relation_similarity_threshold", -1.0, "float"),
        CF("graph.expansion_degree", 1, "int"),
        CF("graph.final_top_k", 3, "int"),
        CF("graph.use_llm_rerank", true, "bool"),
      ],
    },
    verify: {
      label: "引用验证",
      description: "三层防线的强度与成本：蕴含判定方式 / 严格模式 / 抽样比例",
      fields: [
        CF("verify.entailment_mode", "llm", "str", "default", false, "蕴含判定方式：llm 逐条调用裁判模型判断结论是否被原文支撑（最严格，也是最大的一笔开销）；skip 跳过该层，只保留引用存在性与文本哈希校验"),
        CF("verify.strict", true, "bool", "default", false, "全量评审所有引用；关闭后按抽样比例送审"),
        CF("verify.sample_ratio", 1.0, "float", "default", false, "非严格模式下送入蕴含判定的引用比例（0~1，确定性均匀取样）"),
      ],
    },
    retry: {
      label: "重试策略",
      description: "指数退避 + 随机抖动",
      fields: [
        CF("retry.max_attempts", 3, "int"),
        CF("retry.base_delay", 0.5, "float"),
        CF("retry.max_delay", 30.0, "float"),
        CF("retry.jitter", 0.1, "float"),
        CF("retry.backoff_factor", 2.0, "float"),
      ],
    },
    observability: {
      label: "可观测性",
      description: "日志级别、OTel 预留、进程内指标开关",
      fields: [
        CF("observability.log_level", "INFO", "str"),
        CF("observability.tracing_enabled", true, "bool"),
        CF("observability.metrics_enabled", true, "bool"),
      ],
    },
    parsers: {
      label: "解析引擎路由（插拔式）",
      description:
        "双引擎路由开关 + vision 引擎统一配置：engine=auto 按 priority 选择；mineru / docling 同构 enabled（开关）/ mode（免费-付费）/ priority",
      fields: [
        CF("parsers.router_on", true, "bool", "default", false, "PDF 解析分流：文本型 PDF 进入快速通道，扫描件转交 OCR 引擎"),
        CF("parsers.pdf_inspector_on", true, "bool", "default", false, "快速通道：对纯文本 PDF 直接提取文字层"),
        CF("parsers.tsr_on", false, "bool", "default", false, "表格结构还原：识别合并单元格与层级表头"),
        CF("parsers.rotation_on", true, "bool", "default", false, "扫描件方向校正：当前仅作为标记写入解析元数据，内置 MinerU 引擎尚未消费"),
        CF("parsers.engine", "auto", "str", "default", false, "解析引擎选择：auto 表示按优先级自动选用"),
        CF("parsers.mineru.enabled", true, "bool", "default", false, "是否启用该引擎；停用后不再占用相关资源"),
        CF("parsers.mineru.mode", "free", "str", "default", false, "运行模式：使用免费额度或付费服务"),
        CF("parsers.mineru.priority", 100, "int", "default", false, "优先级：auto 模式下数值越小越优先选用"),
        CF("parsers.docling.enabled", false, "bool", "default", false, "是否启用该引擎；停用后不再占用相关资源"),
        CF("parsers.docling.mode", "local", "str", "default", false, "运行模式：local 使用本地模型，api 调用云端服务"),
        CF("parsers.docling.priority", 200, "int", "default", false, "优先级：auto 模式下数值越小越优先选用"),
      ],
    },
    mineru: {
      label: "MinerU 文档解析",
      description: "provider=cli（本机 CLI）或 http（API），OCR / 表格 / 公式开关",
      fields: [
        CF("mineru.provider", "cli", "str"),
        CF("mineru.executable", "mineru-open-api", "str"),
        CF("mineru.api_base", "https://mineru.net", "str"),
        CF("mineru.api_key", "", "str", "default", true),
        CF("mineru.model_version", "vlm", "str"),
        CF("mineru.language", "ch", "str"),
        CF("mineru.enable_ocr", true, "bool"),
        CF("mineru.enable_table", true, "bool"),
        CF("mineru.enable_formula", true, "bool"),
        CF("mineru.page_limit", 200, "int"),
        CF("mineru.timeout", 900.0, "float"),
      ],
    },
    docling: {
      label: "Docling 引擎专属配置",
      description: "mode=api 云服务端点与凭据（local 本地模型无需配置）",
      fields: [
        CF("docling.api_base", "", "str"),
        CF("docling.api_key", "", "str", "default", true),
      ],
    },
    catalog: {
      label: "目录服务",
      description: "SQLAlchemy + SQLite：租户关系 / 文档状态机库路径、自动打标签 / 过滤开关",
      fields: [
        CF("catalog.db_path", "data/rag4c.db", "str"),
        CF("catalog.auto_filter_on", false, "bool"),
        CF("catalog.auto_tag_on", false, "bool"),
      ],
    },
    tenant: {
      label: "多租户隔离",
      description: "强制隔离开关与匿名默认租户（跨租户数据不可见）",
      fields: [
        CF("tenant.enforced", true, "bool"),
        CF("tenant.default_tenant", "default", "str"),
      ],
    },
    circuit: {
      label: "熔断器",
      description: "依赖故障隔离：连续失败阈值 / 冷却时长 / 半开探测数",
      fields: [
        CF("circuit.failure_threshold", 3, "int"),
        CF("circuit.cooldown_s", 30.0, "float"),
        CF("circuit.half_open_probe", 1, "int"),
      ],
    },
  },
  engines: {
    choice: "auto",
    active: "mineru",
    plugins: [
      {
        name: "mineru",
        describe: "MinerU OCR / 版面解析（free=flash-extract 免 token；paid=v4 精准，需 API Token）",
        modes: ["free", "paid"],
        configured: true,
        enabled: true,
        mode: "free",
        priority: 100,
      },
      {
        name: "docling",
        describe: "IBM Docling（local=本地 AI 模型免费；api=云服务付费，预留）",
        modes: ["local", "api"],
        configured: true,
        enabled: false,
        mode: "local",
        priority: 200,
      },
    ],
  },
};
