// @vitest-environment jsdom
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { DocumentChunkItem, DocumentDetail } from "../../types/rag";
import type { ParseScope } from "../model/parseInterventionModel";
const api = vi.hoisted(() => ({ fetchParseChunkPage: vi.fn(), fetchParseChunkDetail: vi.fn(), patchParseChunk: vi.fn(), tombstoneParseChunk: vi.fn() }));
vi.mock("../api/parseInterventionApi", () => api);
import { useParseIntervention } from "./useParseIntervention";
const scopeA: ParseScope = { tenantId: "tenant-a", datasetId: "dataset-a", actorToken: "token-a", docId: "doc-a" };
const scopeB: ParseScope = { tenantId: "tenant-b", datasetId: "dataset-b", actorToken: "token-b", docId: "doc-b" };
const document = { id:"doc-a", name:"Doc", tenant_id:"tenant-a", dataset_id:"dataset-a", status:"completed", status_detail:"", progress:1, chunk_count:250, doc_type:"pdf", error_message:"", file_path:"secret", file_hash:"hash", updated_at:null } as DocumentDetail;
function chunk(id:string, rev=1, overrides:Partial<DocumentChunkItem>={}):DocumentChunkItem{return {chunk_id:id,doc_id:"doc-a",tenant_id:"tenant-a",dataset_id:"dataset-a",text:`body ${id}`,text_hash:"h",content_revision:rev,document_revision:3,enabled:true,chunk_role:"flat",seq:Number(id.split("-").pop()||0),context:"",char_count:5,parent_relation:"none",metadata:{},...overrides};}
function page(items:DocumentChunkItem[], total=items.length, offset=0){return {authority_mode:"active" as const,items,total,offset,limit:100,known_parent_ids:[],missing_parent_ids:[]};}
beforeEach(()=>{vi.clearAllMocks();api.fetchParseChunkPage.mockResolvedValue(page([chunk("chunk-0"), chunk("chunk-1")],2));}); afterEach(cleanup);
describe("useParseIntervention scoped paging and recovery",()=>{
 it("fails closed without signed scope",()=>{const {result}=renderHook(()=>useParseIntervention({...scopeA,actorToken:""},true,document));expect(result.current.status).toBe("scope-error");expect(api.fetchParseChunkPage).not.toHaveBeenCalled();});
 it("loads and appends server pages while reporting loaded over total",async()=>{api.fetchParseChunkPage.mockResolvedValueOnce(page(Array.from({length:100},(_,i)=>chunk(`chunk-${i}`)),235,0)).mockResolvedValueOnce(page(Array.from({length:100},(_,i)=>chunk(`chunk-${i+100}`)),235,100));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.chunks).toHaveLength(100));expect(result.current.total).toBe(235);expect(result.current.hasMore).toBe(true);await act(async()=>{await result.current.loadMore();});expect(result.current.chunks).toHaveLength(200);expect(api.fetchParseChunkPage).toHaveBeenLastCalledWith(scopeA,expect.objectContaining({offset:100}),expect.any(AbortSignal));});
 it("resets paging and sends search to the server",async()=>{vi.useFakeTimers();const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await act(async()=>{await vi.runAllTimersAsync();});act(()=>result.current.setQuery("policy"));await act(async()=>{await vi.runAllTimersAsync();});expect(api.fetchParseChunkPage).toHaveBeenLastCalledWith(scopeA,expect.objectContaining({offset:0,query:"policy"}),expect.any(AbortSignal));vi.useRealTimers();});
 it("keeps a missing conflict draft independent of selection until discard",async()=>{api.patchParseChunk.mockRejectedValue(Object.assign(new Error("conflict"),{status:409}));api.fetchParseChunkDetail.mockRejectedValue(Object.assign(new Error("missing"),{status:404}));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));act(()=>{result.current.setDraft("local orphan");result.current.setReason("reason");});await act(async()=>{await result.current.submit();});expect(result.current.orphanDraft).toMatchObject({chunkId:"chunk-0",baseRevision:1,originalContent:"body chunk-0",draft:"local orphan",resolution:"missing"});act(()=>result.current.selectChunk("chunk-1"));expect(result.current.selectedId).toBe("chunk-0");await act(async()=>{await result.current.submit()});expect(api.patchParseChunk).toHaveBeenCalledTimes(1);expect(result.current.orphanDraft?.draft).toBe("local orphan");act(()=>result.current.discardOrphanDraft());expect(result.current.orphanDraft).toBeNull();});
 it("makes tombstone conflicts copy/discard only and active receipts do not infer pending from operation ids",async()=>{api.patchParseChunk.mockRejectedValue(Object.assign(new Error("conflict"),{status:409}));api.fetchParseChunkDetail.mockResolvedValue(chunk("chunk-0",2,{enabled:false,authority_mode:"active",operation_ids:["op"]} as Partial<DocumentChunkItem>));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));act(()=>{result.current.setDraft("local");result.current.setReason("reason");});await act(async()=>{await result.current.submit();});expect(result.current.orphanDraft?.resolution).toBe("tombstone");expect(result.current.canRebaseOrphan).toBe(false);});
 it("uses mode-specific receipts and never infers active pending from operation ids",async()=>{
  api.patchParseChunk.mockResolvedValue({...chunk("chunk-0",2),authority_mode:"active",operation_ids:["op"],projection_pending:false,index_status:"ready",indexed_revision:2,desired_index_revision:2});
  const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));act(()=>{result.current.setDraft("edited");result.current.setReason("reason")});await act(async()=>{await result.current.submit()});expect(result.current.receipt?.projectionState).toBe("reported-current");
  api.fetchParseChunkPage.mockResolvedValue({...page([chunk("chunk-0")],1),authority_mode:"shadow"});api.patchParseChunk.mockResolvedValue({...chunk("chunk-0",2),authority_mode:"shadow",operation_ids:["op-shadow"],projection_pending:true});
  const shadow=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(shadow.result.current.status).toBe("ready"));act(()=>{shadow.result.current.setDraft("shadow edit");shadow.result.current.setReason("reason")});await act(async()=>{await shadow.result.current.submit()});expect(shadow.result.current.receipt?.projectionState).toBe("shadow-synchronous");shadow.unmount();
 });
 it("discards stale page results after scope changes",async()=>{let resolve!: (v:ReturnType<typeof page>)=>void;api.fetchParseChunkPage.mockReturnValueOnce(new Promise(r=>{resolve=r})).mockResolvedValueOnce(page([chunk("b",1,{doc_id:"doc-b",tenant_id:"tenant-b",dataset_id:"dataset-b"})]));const {result,rerender}=renderHook(({scope,doc})=>useParseIntervention(scope,true,doc),{initialProps:{scope:scopeA,doc:document}});await waitFor(()=>expect(api.fetchParseChunkPage).toHaveBeenCalledTimes(1));rerender({scope:scopeB,doc:{...document,id:"doc-b",tenant_id:"tenant-b",dataset_id:"dataset-b"}});await act(async()=>resolve(page([chunk("stale")])));await waitFor(()=>expect(result.current.chunks[0]?.chunk_id).toBe("b"));});
});
