// @vitest-environment jsdom
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { DocumentChunkItem, DocumentDetail } from "../../types/rag";
import type { ParseScope } from "../model/parseInterventionModel";
const api = vi.hoisted(() => ({ fetchParseChunkPage: vi.fn(), fetchParseChunkDetail: vi.fn(), patchParseChunk: vi.fn(), tombstoneParseChunk: vi.fn(), setParseChunkEnabled: vi.fn(), fetchParseChunkRevisions: vi.fn(), revertParseChunk: vi.fn() }));
vi.mock("../api/parseInterventionApi", () => api);
import { useParseIntervention } from "./useParseIntervention";
const scopeA: ParseScope = { tenantId: "tenant-a", datasetId: "dataset-a", actorToken: "token-a", docId: "doc-a" };
const scopeB: ParseScope = { tenantId: "tenant-b", datasetId: "dataset-b", actorToken: "token-b", docId: "doc-b" };
const document = { id:"doc-a", name:"Doc", tenant_id:"tenant-a", dataset_id:"dataset-a", status:"completed", status_detail:"", progress:1, chunk_count:250, doc_type:"pdf", error_message:"", file_path:"secret", file_hash:"hash", updated_at:null } as DocumentDetail;
function chunk(id:string, rev=1, overrides:Partial<DocumentChunkItem>={}):DocumentChunkItem{return {chunk_id:id,doc_id:"doc-a",tenant_id:"tenant-a",dataset_id:"dataset-a",text:`body ${id}`,text_hash:"h",content_revision:rev,document_revision:3,enabled:true,chunk_role:"flat",seq:Number(id.split("-").pop()||0),context:"",char_count:5,parent_relation:"none",metadata:{},...overrides};}
function page(items:DocumentChunkItem[], total=items.length, offset=0){return {authority_mode:"active" as const,items,total,offset,limit:100,known_parent_ids:[],missing_parent_ids:[]};}
beforeEach(()=>{vi.clearAllMocks();api.fetchParseChunkPage.mockResolvedValue(page([chunk("chunk-0"), chunk("chunk-1")],2));}); afterEach(cleanup);
describe("useParseIntervention scoped paging and recovery",()=>{
 it("fails closed without signed scope",()=>{const {result}=renderHook(()=>useParseIntervention({...scopeA,actorToken:""},true,document));expect(result.current.status).toBe("scope-error");expect(api.fetchParseChunkPage).not.toHaveBeenCalled();});
 it("loads and appends server pages while reporting loaded over total",async()=>{api.fetchParseChunkPage.mockResolvedValueOnce(page(Array.from({length:100},(_,i)=>chunk(`chunk-${i}`)),235,0)).mockResolvedValueOnce(page(Array.from({length:100},(_,i)=>chunk(`chunk-${i+100}`)),235,100));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.chunks).toHaveLength(100));expect(result.current.total).toBe(235);expect(result.current.hasMore).toBe(true);await act(async()=>{await result.current.loadMore();});expect(result.current.chunks).toHaveLength(200);expect(api.fetchParseChunkPage).toHaveBeenLastCalledWith(scopeA,expect.objectContaining({offset:100}),expect.any(AbortSignal));});
 it("resets paging and sends search to the server",async()=>{vi.useFakeTimers();const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await act(async()=>{await vi.runAllTimersAsync();});act(()=>result.current.setQuery("policy"));await act(async()=>{await vi.runAllTimersAsync();});expect(api.fetchParseChunkPage).toHaveBeenLastCalledWith(scopeA,expect.objectContaining({offset:0,query:"policy"}),expect.any(AbortSignal));vi.useRealTimers();});
 it("keeps a missing conflict draft independent of selection until discard",async()=>{api.patchParseChunk.mockRejectedValue(Object.assign(new Error("conflict"),{status:409}));api.fetchParseChunkDetail.mockRejectedValue(Object.assign(new Error("missing"),{status:404}));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));act(()=>{result.current.setDraft("local orphan");result.current.setReason("reason");});await act(async()=>{await result.current.submit();});expect(result.current.orphanDraft).toMatchObject({chunkId:"chunk-0",baseRevision:1,originalContent:"body chunk-0",draft:"local orphan",resolution:"missing"});act(()=>result.current.selectChunk("chunk-1"));expect(result.current.selectedId).toBe("chunk-0");await act(async()=>{await result.current.submit()});expect(api.patchParseChunk).toHaveBeenCalledTimes(1);expect(result.current.orphanDraft?.draft).toBe("local orphan");act(()=>result.current.discardOrphanDraft());expect(result.current.orphanDraft).toBeNull();});
 it("makes tombstone conflicts copy/discard only and active receipts do not infer pending from operation ids",async()=>{api.patchParseChunk.mockRejectedValue(Object.assign(new Error("conflict"),{status:409}));api.fetchParseChunkDetail.mockResolvedValue(chunk("chunk-0",2,{enabled:false,authority_mode:"active",operation_ids:["op"]} as Partial<DocumentChunkItem>));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));act(()=>{result.current.setDraft("local");result.current.setReason("reason");});await act(async()=>{await result.current.submit();});expect(result.current.orphanDraft?.resolution).toBe("tombstone");expect(result.current.canRebaseOrphan).toBe(false);});
 it("uses mode-specific receipts and never infers active pending from operation ids",async()=>{
  api.patchParseChunk.mockResolvedValue({...chunk("chunk-0",2),authority_mode:"active",operation_ids:["op"],projection_pending:false,index_status:"ready",indexed_revision:2,desired_index_revision:2});
  const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));act(()=>{result.current.setDraft("edited");result.current.setReason("reason")});await act(async()=>{await result.current.submit()});expect(result.current.receipt?.projectionState).toBe("reported-current");
  api.fetchParseChunkPage.mockResolvedValue({...page([chunk("chunk-0")],1),authority_mode:"shadow"});api.patchParseChunk.mockResolvedValue({...chunk("chunk-0",2),authority_mode:"shadow",operation_ids:["op-shadow"],projection_pending:true});
  const shadow=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(shadow.result.current.status).toBe("ready"));act(()=>{shadow.result.current.setDraft("shadow edit");shadow.result.current.setReason("reason")});await act(async()=>{await shadow.result.current.submit()});expect(shadow.result.current.receipt?.projectionState).toBe("shadow-synchronous");shadow.unmount();
 });
 it("discards stale page results after scope changes",async()=>{let resolve!: (v:ReturnType<typeof page>)=>void;api.fetchParseChunkPage.mockReturnValueOnce(new Promise(r=>{resolve=r})).mockResolvedValueOnce(page([chunk("b",1,{doc_id:"doc-b",tenant_id:"tenant-b",dataset_id:"dataset-b"})]));const {result,rerender}=renderHook(({scope,doc})=>useParseIntervention(scope,true,doc),{initialProps:{scope:scopeA,doc:document}});await waitFor(()=>expect(api.fetchParseChunkPage).toHaveBeenCalledTimes(1));rerender({scope:scopeB,doc:{...document,id:"doc-b",tenant_id:"tenant-b",dataset_id:"dataset-b"}});await act(async()=>resolve(page([chunk("stale")])));await waitFor(()=>expect(result.current.chunks[0]?.chunk_id).toBe("b"));});
 it("un-tombstones a read-only chunk so the editor leaves 墓碑 state",async()=>{api.fetchParseChunkPage.mockResolvedValue(page([chunk("chunk-0",3,{enabled:false})],1));api.setParseChunkEnabled.mockResolvedValue(chunk("chunk-0",4,{enabled:true}));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));expect(result.current.selected?.enabled).toBe(false);act(()=>result.current.setReason("误删恢复"));await act(async()=>{await result.current.setEnabled(true);});expect(api.setParseChunkEnabled).toHaveBeenCalledWith(scopeA,"chunk-0",true,3,"误删恢复",expect.any(AbortSignal));expect(result.current.selected?.enabled).toBe(true);expect(result.current.expectedRevision).toBe(4);expect(result.current.receipt?.kind).toBe("edit");expect(result.current.reason).toBe("");});
 it("requires a reason for enable/disable and routes 409 into the orphan draft path",async()=>{api.fetchParseChunkPage.mockResolvedValue(page([chunk("chunk-0",3,{enabled:false})],1));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));await act(async()=>{expect(await result.current.setEnabled(true)).toBe(false);});expect(api.setParseChunkEnabled).not.toHaveBeenCalled();api.setParseChunkEnabled.mockRejectedValue(Object.assign(new Error("conflict"),{status:409}));api.fetchParseChunkDetail.mockResolvedValue(chunk("chunk-0",6,{enabled:false}));act(()=>result.current.setReason("误删恢复"));await act(async()=>{await result.current.setEnabled(true);});expect(result.current.orphanDraft).toMatchObject({chunkId:"chunk-0",baseRevision:3,resolution:"tombstone"});expect(api.fetchParseChunkDetail).toHaveBeenCalledWith(scopeA,"chunk-0",expect.any(AbortSignal));});
 it("loads revision history newest first and reverts as a new revision",async()=>{const rev=(revision:number,content:string,overrides:Partial<{enabled:boolean;edit_source:string}>=({}))=>({revision,content,content_hash:"h"+revision,enabled:overrides.enabled!==false,editor_id:"system:document-workbench",edit_source:overrides.edit_source??"user",edited_at:"2026-09-22T03:04:05.000Z"});api.fetchParseChunkPage.mockResolvedValue(page([chunk("chunk-0",3)],1));api.fetchParseChunkRevisions.mockResolvedValue({chunk_id:"chunk-0",items:[rev(1,"v1"),rev(2,"v2"),rev(3,"v3")]});api.revertParseChunk.mockResolvedValue(chunk("chunk-0",4,{text:"v2"}));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));expect(result.current.revisions).toHaveLength(0);await act(async()=>{await result.current.loadRevisions();});expect(result.current.revisions.map(x=>x.revision)).toEqual([3,2,1]);expect(result.current.revisions[0]).toMatchObject({isCurrent:true,canRevertTo:false});expect(result.current.revisions[1]).toMatchObject({revision:2,isCurrent:false,canRevertTo:true});act(()=>result.current.setReason("回到第二版"));await act(async()=>{await result.current.revertTo(2);});expect(api.revertParseChunk).toHaveBeenCalledWith(scopeA,"chunk-0",2,3,"回到第二版",expect.any(AbortSignal));expect(result.current.selected?.text).toBe("v2");expect(result.current.expectedRevision).toBe(4);expect(result.current.receipt?.kind).toBe("edit");await waitFor(()=>expect(api.fetchParseChunkRevisions).toHaveBeenCalledTimes(2));});
 it("refuses to revert a tombstone head and without a reason",async()=>{api.fetchParseChunkPage.mockResolvedValue(page([chunk("chunk-0",3,{enabled:false})],1));const {result}=renderHook(()=>useParseIntervention(scopeA,true,document));await waitFor(()=>expect(result.current.status).toBe("ready"));act(()=>result.current.setReason("回到第二版"));await act(async()=>{expect(await result.current.revertTo(2)).toBe(false);});expect(api.revertParseChunk).not.toHaveBeenCalled();});
 it("selects the deep linked chunk once the page arrives",async()=>{const {result}=renderHook(()=>useParseIntervention(scopeA,true,document,"chunk-1"));await waitFor(()=>expect(result.current.status).toBe("ready"));expect(result.current.selectedId).toBe("chunk-1");expect(result.current.selected?.chunk_id).toBe("chunk-1");expect(result.current.draft).toBe("body chunk-1");expect(result.current.expectedRevision).toBe(1);});
 it("keeps the operator selection after the deep link was applied once",async()=>{const {result}=renderHook(()=>useParseIntervention(scopeA,true,document,"chunk-1"));await waitFor(()=>expect(result.current.selectedId).toBe("chunk-1"));act(()=>result.current.selectChunk("chunk-0"));expect(result.current.selectedId).toBe("chunk-0");await act(async()=>{await result.current.reload();});expect(result.current.selectedId).toBe("chunk-0");});
});

