import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { DocumentChunkItem, DocumentChunkRevisionItem, DocumentDetail, DocumentChunkUpdateResponse, DocumentChunkDeleteResponse } from "../../types/rag";
import { fetchParseChunkDetail, fetchParseChunkPage, fetchParseChunkRevisions, patchParseChunk, revertParseChunk, setParseChunkEnabled, tombstoneParseChunk } from "../api/parseInterventionApi";
import { projectChunkRevisions, projectProjectionLifecycle, requireParseScope, type ChunkRevisionRow, type ParseScope } from "../model/parseInterventionModel";

export type ParseLoadStatus = "scope-error"|"offline"|"loading"|"ready"|"error";
export interface ParseFilters { lifecycle:"all"|"enabled"|"tombstone"; projection:"all"|"current"|"pending"|"failed"|"unknown"; relation:"all"|"flat"|"child"; warningsOnly:boolean; showTombstones:boolean; }
export interface OrphanDraft { chunkId:string; originalContent:string; draft:string; reason:string; baseRevision:number; server:DocumentChunkItem|null; resolution:"conflict"|"missing"|"tombstone"; }
export interface ParseProjectionReceipt { kind:"edit"|"delete"; authorityAccepted:true; authorityMode:"shadow"|"active"; projectionState:"pending"|"reported-current"|"shadow-synchronous"; operationIds:string[]; reason:string; message:string; }
const DEFAULT_FILTERS:ParseFilters={lifecycle:"all",projection:"all",relation:"all",warningsOnly:false,showTombstones:false};
const PAGE_SIZE=100;
function statusOf(e:unknown){return typeof e==="object"&&e!==null&&"status" in e?Number(e.status):0;}
function codeOf(e:unknown){if(typeof e!=="object"||e===null||!("body" in e))return "";const b=e.body as {detail?:{code?:unknown};error?:{code?:unknown}};return String(b?.detail?.code??b?.error?.code??"");}
function messageOf(e:unknown){return e instanceof Error?e.message:String(e);}
function replace(items:DocumentChunkItem[],item:DocumentChunkItem){const found=items.some(x=>x.chunk_id===item.chunk_id);return found?items.map(x=>x.chunk_id===item.chunk_id?item:x):[item,...items];}
function receipt(kind:"edit"|"delete",r:DocumentChunkUpdateResponse|DocumentChunkDeleteResponse,reason:string):ParseProjectionReceipt{
 const mode=r.authority_mode==="shadow"?"shadow":"active"; const pending=mode==="active"&&r.projection_pending===true;
 return {kind,authorityAccepted:true,authorityMode:mode,projectionState:mode==="shadow"?"shadow-synchronous":pending?"pending":"reported-current",operationIds:r.operation_ids??[],reason,message:mode==="shadow"?"权威 Revision 已记录；当前为 shadow 模式，旧 Milvus/图谱投影在请求内同步更新，仍需一致性检查。":pending?"ChunkHead CAS 已提交；持久投影仍在排队或处理中，请在一致性控制台确认收敛。":"ChunkHead CAS 已提交；响应未报告待处理投影，仍需一致性检查。"};
}
export function useParseIntervention(input:ParseScope|null,online:boolean|null,document:DocumentDetail|null=null,initialChunkId:string|null=null){
 const tenantId=input?.tenantId.trim()??"",datasetId=input?.datasetId.trim()??"",actorToken=input?.actorToken?.trim()??"",docId=input?.docId.trim()??"";
 const scope=useMemo(()=>requireParseScope({tenantId,datasetId,actorToken,docId}),[tenantId,datasetId,actorToken,docId]);
 const key=scope?`${tenantId}\0${datasetId}\0${actorToken}\0${docId}`:""; const keyRef=useRef(key);keyRef.current=key;
 const loadRef=useRef<AbortController|null>(null),mutationRef=useRef<AbortController|null>(null),revisionsRef=useRef<AbortController|null>(null),detailRef=useRef<AbortController|null>(null),revisionsForRef=useRef(""),seqRef=useRef(0),editorRef=useRef(""),initialAppliedRef=useRef("");
 const [status,setStatus]=useState<ParseLoadStatus>(!scope?"scope-error":online===false?"offline":"loading"),[chunks,setChunks]=useState<DocumentChunkItem[]>([]),[total,setTotal]=useState(0),[authorityMode,setAuthorityMode]=useState<"off"|"shadow"|"active">("active"),[knownParents,setKnownParents]=useState<Set<string>>(new Set()),[missingParents,setMissingParents]=useState<Set<string>>(new Set());
 const [selectedId,setSelectedId]=useState(""),[query,setQuery]=useState(""),[filters,setFilters]=useState<ParseFilters>(DEFAULT_FILTERS),[draft,setDraft]=useState(""),[reason,setReason]=useState(""),[expectedRevision,setExpectedRevision]=useState(0),[error,setError]=useState(""),[mutating,setMutating]=useState(false),[loadingMore,setLoadingMore]=useState(false),[receiptState,setReceipt]=useState<ParseProjectionReceipt|null>(null),[orphanDraft,setOrphanDraft]=useState<OrphanDraft|null>(null);
 const [revisionsFor,setRevisionsFor]=useState(""),[revisionsRaw,setRevisionsRaw]=useState<DocumentChunkRevisionItem[]>([]),[revisionsLoading,setRevisionsLoading]=useState(false),[revisionsError,setRevisionsError]=useState(""),[detailLoading,setDetailLoading]=useState(false);
 const applyPage=useCallback((page:Awaited<ReturnType<typeof fetchParseChunkPage>>,append:boolean)=>{setAuthorityMode(page.authority_mode??"active");setTotal(page.total);setKnownParents(p=>new Set([...p,...(page.known_parent_ids??[])]));setMissingParents(p=>new Set([...p,...(page.missing_parent_ids??[])]));setChunks(cur=>{const base=append?cur:[];const map=new Map(base.map(x=>[x.chunk_id,x]));for(const item of page.items)map.set(item.chunk_id,item);return [...map.values()];});setStatus("ready");setError("");},[]);
 const fetchPage=useCallback(async(offset:number,append:boolean,search=query)=>{if(!scope||online!==true)return false;loadRef.current?.abort();const c=new AbortController();loadRef.current=c;const requestKey=key,seq=++seqRef.current;if(append)setLoadingMore(true);else{setStatus("loading");setChunks([]);setTotal(0);setKnownParents(new Set());setMissingParents(new Set());}try{const page=await fetchParseChunkPage(scope,{offset,limit:PAGE_SIZE,query:search,includeDisabled:true},c.signal);if(c.signal.aborted||keyRef.current!==requestKey||seq!==seqRef.current)return false;applyPage(page,append);return true;}catch(e){if(c.signal.aborted||keyRef.current!==requestKey)return false;if(codeOf(e)==="knowledge_chunk_authority_unavailable")setAuthorityMode("off");setStatus("error");setError(messageOf(e));return false;}finally{if(loadRef.current===c)loadRef.current=null;if(keyRef.current===requestKey)setLoadingMore(false);}},[applyPage,key,online,query,scope]);
 useEffect(()=>{loadRef.current?.abort();mutationRef.current?.abort();revisionsRef.current?.abort();detailRef.current?.abort();setSelectedId("");setDraft("");setReason("");setOrphanDraft(null);setReceipt(null);setRevisionsFor("");setRevisionsRaw([]);setRevisionsError("");revisionsForRef.current="";if(!scope){setStatus("scope-error");return;}if(online!==true){setStatus(online===false?"offline":"loading");return;}const timer=setTimeout(()=>void fetchPage(0,false,query),query?200:0);return()=>{clearTimeout(timer);loadRef.current?.abort();mutationRef.current?.abort();revisionsRef.current?.abort();detailRef.current?.abort();};},[key,online,query,scope,fetchPage]);
 const selected=useMemo(()=>chunks.find(x=>x.chunk_id===selectedId)??chunks[0]??null,[chunks,selectedId]);
 useEffect(()=>{if(!selected||orphanDraft)return;const ek=`${selected.chunk_id}\0${selected.content_revision}`;if(editorRef.current===ek)return;editorRef.current=ek;setSelectedId(selected.chunk_id);setDraft(selected.text);setReason("");setExpectedRevision(selected.content_revision);},[selected,orphanDraft]);
 useEffect(()=>{if(!initialChunkId||orphanDraft||!scope||online!==true)return;const stamp=`${key}\0${initialChunkId}`;if(initialAppliedRef.current===stamp)return;if(chunks.some(x=>x.chunk_id===initialChunkId)){initialAppliedRef.current=stamp;setSelectedId(initialChunkId);return;}if(status!=="ready")return;initialAppliedRef.current=stamp;const c=new AbortController();detailRef.current=c;setDetailLoading(true);fetchParseChunkDetail(scope,initialChunkId,c.signal).then(detail=>{if(c.signal.aborted||keyRef.current!==key)return;setChunks(x=>replace(x,detail));setSelectedId(initialChunkId);}).catch(e=>{if(c.signal.aborted||keyRef.current!==key)return;setError(`深链指向的切片 ${initialChunkId} 打不开：${messageOf(e)}`);}).finally(()=>{if(detailRef.current===c)detailRef.current=null;if(keyRef.current===key)setDetailLoading(false);});},[chunks,initialChunkId,key,online,orphanDraft,scope,status]);
 const revisions=useMemo<ChunkRevisionRow[]>(()=>selected&&revisionsFor===selected.chunk_id?projectChunkRevisions(revisionsRaw,selected.content_revision):[],[revisionsFor,revisionsRaw,selected]);
 const editorReady=Boolean(selected)&&editorRef.current===`${selected?.chunk_id}\0${selected?.content_revision}`; const dirty=editorReady&&Boolean(selected)&&(draft.trim()!==selected?.text.trim()||reason.trim().length>0); const hasMore=chunks.length<total;
 const loadMore=useCallback(()=>hasMore&&!loadingMore?fetchPage(chunks.length,true):Promise.resolve(false),[chunks.length,fetchPage,hasMore,loadingMore]);
 const selectChunk=useCallback((id:string)=>{if(orphanDraft)return;if(chunks.some(x=>x.chunk_id===id))setSelectedId(id);},[chunks,orphanDraft]);
 const resetDraft=useCallback(()=>{setDraft(selected?.text??"");setReason("");setExpectedRevision(selected?.content_revision??0);},[selected]);
 const applyHead=useCallback((updated:DocumentChunkItem)=>{setChunks(x=>replace(x,updated));setDraft(updated.text);setReason("");setExpectedRevision(updated.content_revision);},[]);
 const fetchRevisions=useCallback(async(chunkId:string)=>{if(!scope||online!==true||!chunkId)return false;const c=new AbortController();revisionsRef.current=c;setRevisionsLoading(true);setRevisionsError("");try{const list=await fetchParseChunkRevisions(scope,chunkId,c.signal);if(c.signal.aborted||keyRef.current!==key)return false;revisionsForRef.current=chunkId;setRevisionsFor(chunkId);setRevisionsRaw(list.items??[]);return true;}catch(e){if(c.signal.aborted||keyRef.current!==key)return false;setRevisionsError(messageOf(e));return false;}finally{if(revisionsRef.current===c)revisionsRef.current=null;if(keyRef.current===key)setRevisionsLoading(false);}},[key,online,scope]);
 const ensureRevisions=useCallback((chunkId:string)=>revisionsForRef.current===chunkId?Promise.resolve(false):fetchRevisions(chunkId),[fetchRevisions]);
 const refreshSelectedDetail=useCallback(()=>{if(!scope||!selected||online!==true||selected.source_content!==undefined)return Promise.resolve(false);const chunkId=selected.chunk_id;detailRef.current?.abort();const c=new AbortController();detailRef.current=c;setDetailLoading(true);return fetchParseChunkDetail(scope,chunkId,c.signal).then(detail=>{if(c.signal.aborted||keyRef.current!==key)return false;setChunks(x=>replace(x,detail));return true;}).catch(e=>{if(c.signal.aborted||keyRef.current!==key)return false;setError(messageOf(e));return false;}).finally(()=>{if(detailRef.current===c)detailRef.current=null;if(keyRef.current===key)setDetailLoading(false);});},[key,online,scope,selected]);
 const captureConflict=useCallback(async(head:DocumentChunkItem,controller:AbortController)=>{if(!scope)return;let server:DocumentChunkItem|null=null,resolution:OrphanDraft["resolution"]="missing";try{server=await fetchParseChunkDetail(scope,head.chunk_id,controller.signal);resolution=server.enabled===false?"tombstone":"conflict";}catch(detail){if(statusOf(detail)!==404)setError(messageOf(detail));}setOrphanDraft({chunkId:head.chunk_id,originalContent:head.text,draft,reason,baseRevision:expectedRevision,server,resolution});},[draft,expectedRevision,reason,scope]);
 const submit=useCallback(async()=>{if(!scope||!selected||orphanDraft||selected.enabled===false||mutating||!draft.trim()||draft.trim()===selected.text.trim()||!reason.trim())return false;const c=new AbortController();mutationRef.current=c;setMutating(true);setError("");try{const updated=await patchParseChunk(scope,selected.chunk_id,draft.trim(),expectedRevision,reason.trim(),c.signal);if(c.signal.aborted||keyRef.current!==key)return false;applyHead(updated);setReceipt(receipt("edit",updated,reason.trim()));if(revisionsForRef.current===selected.chunk_id)void fetchRevisions(selected.chunk_id);return true;}catch(e){if(c.signal.aborted||keyRef.current!==key)return false;if(statusOf(e)===409){await captureConflict(selected,c);return false;}setError(messageOf(e));return false;}finally{if(mutationRef.current===c)mutationRef.current=null;if(keyRef.current===key)setMutating(false);}},[applyHead,captureConflict,draft,expectedRevision,key,fetchRevisions,mutating,orphanDraft,reason,scope,selected]);
 const setEnabled=useCallback(async(next:boolean)=>{if(!scope||!selected||orphanDraft||selected.enabled===next||mutating||!reason.trim())return false;const note=reason.trim(),chunkId=selected.chunk_id;const c=new AbortController();mutationRef.current=c;setMutating(true);setError("");try{const updated=await setParseChunkEnabled(scope,chunkId,next,expectedRevision,note,c.signal);if(c.signal.aborted||keyRef.current!==key)return false;applyHead(updated);setReceipt(receipt(next?"edit":"delete",updated,note));if(revisionsForRef.current===chunkId)void fetchRevisions(chunkId);return true;}catch(e){if(c.signal.aborted||keyRef.current!==key)return false;if(statusOf(e)===409){await captureConflict(selected,c);return false;}setError(messageOf(e));return false;}finally{if(mutationRef.current===c)mutationRef.current=null;if(keyRef.current===key)setMutating(false);}},[applyHead,captureConflict,expectedRevision,key,fetchRevisions,mutating,orphanDraft,reason,scope,selected]);
 const revertTo=useCallback(async(targetRevision:number)=>{if(!scope||!selected||orphanDraft||selected.enabled===false||mutating||!reason.trim())return false;const note=reason.trim(),chunkId=selected.chunk_id;const c=new AbortController();mutationRef.current=c;setMutating(true);setError("");try{const updated=await revertParseChunk(scope,chunkId,targetRevision,expectedRevision,note,c.signal);if(c.signal.aborted||keyRef.current!==key)return false;applyHead(updated);setReceipt(receipt("edit",updated,note));void fetchRevisions(chunkId);return true;}catch(e){if(c.signal.aborted||keyRef.current!==key)return false;if(statusOf(e)===409){await captureConflict(selected,c);return false;}setError(messageOf(e));return false;}finally{if(mutationRef.current===c)mutationRef.current=null;if(keyRef.current===key)setMutating(false);}},[applyHead,captureConflict,expectedRevision,key,fetchRevisions,mutating,orphanDraft,reason,scope,selected]);
 const removeSelected=useCallback(async()=>{if(!scope||!selected||selected.enabled===false||mutating)return false;const c=new AbortController();mutationRef.current=c;setMutating(true);try{const result=await tombstoneParseChunk(scope,selected.chunk_id,expectedRevision,c.signal);if(c.signal.aborted||keyRef.current!==key)return false;setChunks(x=>replace(x,{...selected,...result,enabled:false} as unknown as DocumentChunkItem));setReceipt(receipt("delete",result,reason.trim()||"删除切片"));return true;}catch(e){if(c.signal.aborted||keyRef.current!==key)return false;if(statusOf(e)===409){await captureConflict(selected,c);return false;}setError(messageOf(e));return false;}finally{if(mutationRef.current===c)mutationRef.current=null;if(keyRef.current===key)setMutating(false);}},[captureConflict,expectedRevision,key,mutating,reason,scope,selected]);
 const discardOrphanDraft=()=>setOrphanDraft(null); const canRebaseOrphan=orphanDraft?.resolution==="conflict"&&orphanDraft.server?.enabled!==false;
 const rebaseOrphanDraft=()=>{if(!orphanDraft||!canRebaseOrphan||!orphanDraft.server)return;setChunks(x=>replace(x,orphanDraft.server!));setSelectedId(orphanDraft.chunkId);setDraft(orphanDraft.draft);setReason(orphanDraft.reason);setExpectedRevision(orphanDraft.server.content_revision);editorRef.current=`${orphanDraft.chunkId}\0${orphanDraft.server.content_revision}`;setOrphanDraft(null);};
 return {status,document,chunks,total,authorityMode,knownParents,missingParents,selected,selectedId,query,filters,draft,reason,expectedRevision,dirty,error,orphanDraft,receipt:receiptState,mutating,loadingMore,hasMore,canRebaseOrphan,revisions,revisionsLoading,revisionsError,revisionsReady:Boolean(selected)&&revisionsFor===selected?.chunk_id,detailLoading,refreshSelectedDetail,setQuery,setFilters,setDraft,setReason,selectChunk,resetDraft,loadMore,reload:()=>fetchPage(0,false),submit,setEnabled,revertTo,removeSelected,discardOrphanDraft,rebaseOrphanDraft,loadRevisions:()=>selected?fetchRevisions(selected.chunk_id):Promise.resolve(false),ensureRevisions:()=>selected?ensureRevisions(selected.chunk_id):Promise.resolve(false),adoptServer:()=>{if(orphanDraft?.server){setChunks(x=>replace(x,orphanDraft.server!));setSelectedId(orphanDraft.chunkId);setOrphanDraft(null);}},continueDraft:rebaseOrphanDraft,dismissReceipt:()=>setReceipt(null),selectedProjection:selected?projectProjectionLifecycle(selected):null};
}
export type UseParseInterventionResult=ReturnType<typeof useParseIntervention>;
