"""Security helpers for KnowledgeOps rollout reports and resume cursors."""

from __future__ import annotations

import argparse
import base64
import binascii
import json
import re
import secrets
from collections.abc import Mapping, Sequence
from datetime import datetime
from typing import Any

REPORT_SECRET_ENV = "RAG4C_ROLLOUT_REPORT_SECRET"
REPORT_SECRET_ERROR = (
    f"{REPORT_SECRET_ENV} must be a canonical CSPRNG-generated Base64URL key "
    "decoding to at least 32 bytes"
)
_BASE64URL_RE = re.compile(r"^[A-Za-z0-9_-]+$")
_HEX_RE = re.compile(r"^[0-9A-Fa-f]+$")
_SHA256_HEX_RE = re.compile(r"^[0-9a-f]{64}$")
_CURSOR_TIMESTAMP_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}$")
_WEAK_MARKERS = (
    "example",
    "changeme",
    "change-me",
    "replace-me",
    "your-secret",
    "password",
)


def generate_rollout_secret(byte_count: int = 32) -> str:
    """Return an unpadded Base64URL key generated by the OS CSPRNG."""
    if byte_count < 32:
        raise ValueError("rollout secret generation requires at least 32 bytes")
    return base64.urlsafe_b64encode(secrets.token_bytes(byte_count)).decode("ascii").rstrip("=")


def _is_repeated_pattern(value: str) -> bool:
    for width in range(1, min(16, len(value) // 2) + 1):
        if len(value) % width == 0 and value == value[:width] * (len(value) // width):
            return True
    return False


def _is_sequential(value: str) -> bool:
    if len(value) < 16:
        return False
    deltas = [ord(right) - ord(left) for left, right in zip(value, value[1:])]
    ascending = sum(delta == 1 for delta in deltas)
    descending = sum(delta == -1 for delta in deltas)
    return max(ascending, descending) / len(deltas) >= 0.85


def decode_canonical_base64url_json(value: str, *, error_message: str) -> dict[str, Any]:
    """Decode one strict, canonical, unpadded Base64URL JSON object."""
    token = str(value or "")
    if not token or token != token.strip() or not _BASE64URL_RE.fullmatch(token):
        raise ValueError(error_message)
    try:
        padded = token + "=" * (-len(token) % 4)
        decoded = base64.b64decode(padded, altchars=b"-_", validate=True)
        canonical_token = base64.urlsafe_b64encode(decoded).decode("ascii").rstrip("=")
        payload = json.loads(decoded.decode("utf-8"))
    except (ValueError, UnicodeDecodeError, json.JSONDecodeError, binascii.Error) as exc:
        raise ValueError(error_message) from exc
    if canonical_token != token or not isinstance(payload, dict):
        raise ValueError(error_message)
    canonical_json = json.dumps(
        payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    if canonical_json != decoded:
        raise ValueError(error_message)
    return payload


def validate_rollout_cursor_fields(
    payload: Mapping[str, Any],
    *,
    expected_version: int,
    error_message: str,
) -> None:
    """Validate exact scalar types and canonical values in a rollout cursor."""

    def invalid() -> None:
        raise ValueError(error_message)

    version = payload.get("v")
    count = payload.get("snapshot_count")
    if type(version) is not int or version != expected_version:
        invalid()
    if type(count) is not int or count < 0:
        invalid()

    for field in (
        "dataset_generation",
        "snapshot_started_at",
        "snapshot_fingerprint",
        "upper_created_at",
        "upper_document_id",
        "last_created_at",
        "last_document_id",
    ):
        if type(payload.get(field)) is not str:
            invalid()

    for field in ("dataset_generation", "snapshot_fingerprint"):
        if _SHA256_HEX_RE.fullmatch(payload[field]) is None:
            invalid()

    def canonical_timestamp(field: str, *, allow_empty: bool) -> None:
        value = payload[field]
        if not value:
            if allow_empty:
                return
            invalid()
        if _CURSOR_TIMESTAMP_RE.fullmatch(value) is None:
            invalid()
        try:
            parsed = datetime.fromisoformat(value)
        except ValueError:
            invalid()
            return
        if parsed.tzinfo is not None or parsed.isoformat(timespec="microseconds") != value:
            invalid()

    canonical_timestamp("snapshot_started_at", allow_empty=False)
    canonical_timestamp("upper_created_at", allow_empty=True)
    canonical_timestamp("last_created_at", allow_empty=True)

    def valid_identifier(value: str) -> bool:
        return bool(
            value
            and len(value) <= 64
            and value == value.strip()
            and all(ord(character) >= 32 and ord(character) != 127 for character in value)
        )

    upper_time = payload["upper_created_at"]
    upper_id = payload["upper_document_id"]
    last_time = payload["last_created_at"]
    last_id = payload["last_document_id"]
    if bool(upper_time) != bool(upper_id) or (upper_id and not valid_identifier(upper_id)):
        invalid()
    if bool(last_time) != bool(last_id) or (last_id and not valid_identifier(last_id)):
        invalid()
    if last_id and not upper_id:
        invalid()


def validate_sha256_hmac(value: Any, *, error_message: str) -> str:
    """Return one canonical lowercase SHA-256 HMAC or fail closed."""
    if type(value) is not str or _SHA256_HEX_RE.fullmatch(value) is None:
        raise ValueError(error_message)
    return value


def validate_rollout_secret(report_secret: str) -> bytes:
    """Validate the deploy-time key format and reject obvious non-random patterns.

    Runtime validation cannot prove randomness. Requiring a canonical Base64URL
    encoding plus rejecting predictable patterns makes accidental human-authored
    keys fail closed; production keys should be created by
    :func:`generate_rollout_secret` or an equivalent secrets manager workflow.
    """
    value = str(report_secret or "")
    if value != value.strip() or not _BASE64URL_RE.fullmatch(value):
        raise ValueError(REPORT_SECRET_ERROR)
    try:
        padded = value + "=" * (-len(value) % 4)
        decoded = base64.b64decode(padded, altchars=b"-_", validate=True)
    except (ValueError, binascii.Error) as exc:
        raise ValueError(REPORT_SECRET_ERROR) from exc
    canonical = base64.urlsafe_b64encode(decoded).decode("ascii").rstrip("=")
    normalized = value.casefold()
    if (
        canonical != value
        or len(decoded) < 32
        or len(set(value)) < 16
        or len(set(decoded)) < 12
        or any(marker in normalized for marker in _WEAK_MARKERS)
        or _is_repeated_pattern(value)
        or _is_sequential(value)
        or _HEX_RE.fullmatch(value) is not None
    ):
        raise ValueError(REPORT_SECRET_ERROR)
    return decoded


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a KnowledgeOps rollout report key")
    subparsers = parser.add_subparsers(dest="command", required=True)
    generate = subparsers.add_parser("generate", help="generate a CSPRNG Base64URL key")
    generate.add_argument("--bytes", dest="byte_count", type=int, default=32)
    args = parser.parse_args(argv)
    try:
        print(generate_rollout_secret(args.byte_count))
    except ValueError as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
