// @vitest-environment jsdom
import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { ApiError } from "../../api/client";
import * as api from "../api/sourcesApi";
import type { SourceRecord, SourceScope } from "../model/sourceModels";
import { useSourceControl } from "./useSourceControl";
vi.mock("../api/sourcesApi");
const scope: SourceScope = { tenantId: "tenant-a", datasetId: "dataset-a", actorToken: "signed" };
const source: SourceRecord = { id: "source-a", tenant_id: "tenant-a", dataset_id: "dataset-a", name: "Docs", kind: "local_dir", config: { path: "C:/docs", extensions: [".md"] }, metadata: {}, status: "active", generation: 2, last_cursor: {}, last_result: {}, last_error: "", last_sync_at: null, created_at: "2026-08-25T00:00:00Z", updated_at: "2026-08-25T00:00:00Z" };
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>((done) => { resolve = done; }); return { promise, resolve }; }
beforeEach(() => { vi.resetAllMocks(); localStorage.clear(); vi.mocked(api.fetchSources).mockResolvedValue({ items: [source], count: 1 }); });
describe("useSourceControl", () => {
  it("fails closed without authenticated scope and stays offline without demo facts", async () => { const closed = renderHook(() => useSourceControl(null, true)); expect(closed.result.current.status).toBe("scope"); expect(api.fetchSources).not.toHaveBeenCalled(); const offline = renderHook(() => useSourceControl(scope, false)); expect(offline.result.current.status).toBe("offline"); expect(offline.result.current.sources).toEqual([]); });
  it("gates old source facts on the first changed-scope render and aborts the old load", async () => { const first = deferred<{ items: SourceRecord[]; count: number }>(); vi.mocked(api.fetchSources).mockReturnValueOnce(first.promise).mockResolvedValueOnce({ items: [{ ...source, id: "source-b", tenant_id: "tenant-b" }], count: 1 }); const view = renderHook(({ currentScope }) => useSourceControl(currentScope, true), { initialProps: { currentScope: scope } }); await waitFor(() => expect(api.fetchSources).toHaveBeenCalledTimes(1)); const oldSignal = vi.mocked(api.fetchSources).mock.calls[0][2]?.signal as AbortSignal; view.rerender({ currentScope: { tenantId: "tenant-b", datasetId: "dataset-b", actorToken: "signed-b" } }); expect(view.result.current.sources).toEqual([]); expect(view.result.current.status).toBe("loading"); await waitFor(() => expect(oldSignal.aborted).toBe(true)); await waitFor(() => expect(view.result.current.sources[0]?.id).toBe("source-b")); first.resolve({ items: [source], count: 1 }); });
  it("loads authoritative sources and refreshes after generation mutations", async () => { vi.mocked(api.disableSource).mockResolvedValue({ ...source, status: "disabled", generation: 3 }); const view = renderHook(() => useSourceControl(scope, true)); await waitFor(() => expect(view.result.current.status).toBe("ready")); await act(() => view.result.current.setEnabled(source, false)); expect(api.disableSource).toHaveBeenCalledWith(scope, "source-a", 2, expect.objectContaining({ signal: expect.any(AbortSignal) })); expect(api.fetchSources).toHaveBeenCalledTimes(2); });
  it("refreshes authoritative facts on 409 and keeps a conflict error", async () => { vi.mocked(api.patchSource).mockRejectedValue(new ApiError("stale", "http", 409, { detail: { code: "knowledge_source_conflict" } })); const view = renderHook(() => useSourceControl(scope, true)); await waitFor(() => expect(view.result.current.status).toBe("ready")); await act(() => view.result.current.update(source, { name: "Renamed" })); expect(api.fetchSources).toHaveBeenCalledTimes(2); expect(view.result.current.error?.kind).toBe("conflict"); });
  it("reuses a durable sync key after a lost response and returns the authoritative acceptance", async () => { vi.mocked(api.syncSourceNow).mockRejectedValueOnce(new ApiError("lost", "network")).mockResolvedValueOnce({ run_id: "run-a", source_id: "source-a", status: "running", trigger: "manual", retry_of_run_id: null, execution_state: "executing", replayed: true }); const view = renderHook(() => useSourceControl(scope, true)); await waitFor(() => expect(view.result.current.status).toBe("ready")); await act(() => view.result.current.sync(source, { force_full: false, dry_run: false })); let accepted: unknown; await act(async () => { accepted = await view.result.current.sync(source, { force_full: false, dry_run: false }); }); expect(vi.mocked(api.syncSourceNow).mock.calls[1][3]).toBe(vi.mocked(api.syncSourceNow).mock.calls[0][3]); expect(accepted).toMatchObject({ run_id: "run-a", execution_state: "executing", replayed: true }); expect(localStorage.getItem("rag4c.source-sync-intents.v1")).toBeNull(); });
});
